/* ══════════════════════════════════════════════════════════════════
   RPG Matematika 7 — Teorie ke všem 21 misím (Ztracený chrám ⛏️)
   Zdroje: RVP ZV, učebnice Odvárko/Kadleček, Hejný (Fraus), MŠMT
   ══════════════════════════════════════════════════════════════════ */
(function(){
'use strict';
window.RPG_LEARN_7 = {

/* ─── Oblast 1: VSTUPNÍ BRÁNA ─────────────────────────────────── */

'1-1': {
 intro: '🏜️ Strážce karavany tě testuje: „Kdo neumí počítat zpaměti, do chrámu nevejde." Zopakuj si základy a projdi branou!',
 sections: [
  { h: 'Proč počítat zpaměti?',
    p: ['Výpočty zpaměti ti ušetří čas u testů, odhadování výsledků a každodenního počítání. Nejde o memorování — jde o pochopení vzorců čísel.',
        'Klíčové jsou dvě věci: znát násobilku do 10 × 10 a umět využívat vlastnosti operací (komutativnost, asociativnost, distributivnost).'] },
  { h: 'Sčítání a odčítání zpaměti',
    p: ['Čísla si rozlož na desítky a jednotky: 47 + 38 = 40 + 30 + 7 + 8 = 70 + 15 = 85.',
        'Trik pro odčítání: 93 − 47 = 93 − 50 + 3 = 46. Odečteme o trochu víc a pak přidáme zpět.',
        'Doplňování do 100: 63 + ? = 100. Řešení: 100 − 63 = 37. Rychlý postup: 63 → 70 (+7) → 100 (+30), dohromady 37.'] },
  { h: 'Násobení a dělení zpaměti',
    p: ['Násobilka je základ. Pokud si nejsi jistý 8 × 7, zkus 8 × 7 = 8 × 5 + 8 × 2 = 40 + 16 = 56.',
        'Násobení desetinným číslem: 4 × 25 = 100 (protože 4 × 25 = 100). 36 × 25 = 36 × 100 ÷ 4 = 900.',
        'Dělení: 360 ÷ 8 = 360 ÷ 4 ÷ 2 = 90 ÷ 2 = 45. Rozlož na jednodušší kroky.'] },
  { h: 'Odhadování výsledků',
    p: ['Před každým výpočtem si odhadni, co by měl výsledek přibližně být. 47 × 98 ≈ 50 × 100 = 5000. Skutečný výsledek: 4606 — odhad byl rozumný.',
        'Odhad zachrání od hrubých chyb: pokud ti vyjde 47 × 98 = 460, víš, že jsi chybil (o 10×).'] },
 ],
 formulas: [
  '<b>a + b = b + a</b> (komutativnost sčítání)',
  '<b>a × b = b × a</b> (komutativnost násobení)',
  '<b>a × (b + c) = a × b + a × c</b> (distributivnost)',
  '<b>(a + b) − c = a + (b − c)</b> (pro odčítání)',
 ],
 examples: [
  { q: 'Spočítej zpaměti: 67 + 48', s: ['67 + 48 = 67 + 40 + 8 = 107 + 8 = <b>115</b>'] },
  { q: 'Spočítej zpaměti: 125 × 8', s: ['125 × 8 = 125 × 4 × 2 = 500 × 2 = <b>1000</b>'] },
  { q: 'Kolik je 15% z 200 zpaměti?', s: ['15% = 10% + 5%', '10% z 200 = 20', '5% z 200 = 10', 'Výsledek: 20 + 10 = <b>30</b>'] },
 ],
 video: null,
},

'1-2': {
 intro: '🏺 Hlíněný džbán skrývá záhadu: kolik vody v něm je? Musíš pracovat s desetinnými čísly.',
 sections: [
  { h: 'Co je desetinné číslo?',
    p: ['Desetinné číslo zapisujeme s desetinnou čárkou (v Česku čárkou, ne tečkou!). Číslo 3,7 znamená 3 celé a 7 desetin = 3 + 7/10.',
        'Každá číslice má svoji místní hodnotu: 12,345 → 1 desítka, 2 jednotky, 3 desetiny, 4 setiny, 5 tisíciny.'] },
  { h: 'Sčítání a odčítání desetinných čísel',
    p: ['Zarovnaj desetinné čárky pod sebe a počítej jako celá čísla: 3,7 + 2,45 → nejprve doplň nuly: 3,70 + 2,45 = 6,15.',
        'Odčítání stejně: 8,3 − 2,76 = 8,30 − 2,76 = 5,54.'] },
  { h: 'Násobení desetinných čísel',
    p: ['Nejprve počítej bez čárek, pak přidej desetinná místa. Počet desetinných míst výsledku = součet desetinných míst obou čísel.',
        'Příklad: 2,3 × 1,4 → 23 × 14 = 322, obě čísla mají dohromady 2 des. místa → výsledek 3,22.',
        'Násobení mocninami 10: 3,7 × 10 = 37; 3,7 × 100 = 370; 3,7 × 0,1 = 0,37.'] },
  { h: 'Dělení desetinných čísel',
    p: ['Dělení desetinným číslem: vydělitel bez čárky → přenásobíme oba členy stejnou mocninou 10.',
        '4,5 ÷ 0,3 = 45 ÷ 3 = 15. Nebo: 8,4 ÷ 1,2 = 84 ÷ 12 = 7.',
        'Při dělení desetinným číslem se dá říct: dělení je totéž co násobení převrácenou hodnotou.'] },
  { h: 'Zaokrouhlování',
    p: ['Zaokrouhlujeme podle číslice za daným místem: 0–4 dolů, 5–9 nahoru.',
        '3,746 zaokrouhleno na setiny = 3,75. Na desetiny = 3,7. Na jednotky = 4.'] },
 ],
 formulas: [
  '<b>a,bc × 10 = ab,c</b> (posun čárky o 1 vpravo)',
  '<b>a,bc ÷ 10 = 0,abc</b> (posun čárky o 1 vlevo)',
  '<b>a,b × c,d:</b> počet des. míst výsledku = (des. místa a,b) + (des. místa c,d)',
 ],
 examples: [
  { q: 'Spočítej: 5,08 + 3,7', s: ['5,08 + 3,70 = <b>8,78</b>'] },
  { q: 'Spočítej: 2,4 × 3,5', s: ['24 × 35 = 840, celkem 2 desetinná místa → <b>8,40</b>'] },
  { q: 'Spočítej: 9,6 ÷ 0,4', s: ['96 ÷ 4 = <b>24</b>'] },
 ],
 video: null,
},

'1-3': {
 intro: '🧱 Kamenná dlažice má záhadné rozměry. Vypočítej obvody a obsahy, abys prošel dál.',
 sections: [
  { h: 'Obvod rovinného obrazce',
    p: ['Obvod je celková délka hranice obrazce — prostě sečteš délky všech stran.',
        'Pro pravidelné obrazce platí jednoduché vzorce (viz níže).'] },
  { h: 'Čtverec a obdélník',
    p: ['Čtverec se stranou a: obvod o = 4a, obsah S = a².',
        'Obdélník se stranami a, b: obvod o = 2(a + b) = 2a + 2b, obsah S = a · b.'] },
  { h: 'Trojúhelník a rovnoběžník',
    p: ['Trojúhelník se stranami a, b, c: obvod o = a + b + c. Obsah S = (a · h_a) / 2, kde h_a je výška na stranu a.',
        'Rovnoběžník se stranou a a výškou h: obsah S = a · h. Pozor: výška je kolmá vzdálenost rovnoběžných stran, ne délka šikmé strany!'] },
  { h: 'Jednotky délky a obsahu',
    p: ['Délka: 1 km = 1000 m = 100 000 cm = 1 000 000 mm.',
        'Obsah (plošné jednotky): 1 m² = 10 000 cm². Pozor — při přepočtu obsahu musíš umocnit přepočtový koeficient!',
        '1 m² = (100 cm)² = 10 000 cm². 1 km² = 1 000 000 m² = 100 ha.'] },
 ],
 formulas: [
  '<b>Čtverec:</b> o = 4a, S = a²',
  '<b>Obdélník:</b> o = 2(a + b), S = a · b',
  '<b>Trojúhelník:</b> o = a + b + c, S = a · h / 2',
  '<b>Rovnoběžník:</b> S = a · h  (h ⊥ a)',
 ],
 examples: [
  { q: 'Obdélník má strany 8 cm a 5 cm. Jaký je jeho obvod a obsah?', s: ['o = 2 × (8 + 5) = 2 × 13 = <b>26 cm</b>', 'S = 8 × 5 = <b>40 cm²</b>'] },
  { q: 'Trojúhelník má základnu 12 cm a výšku na ni 7 cm. Jaký je obsah?', s: ['S = (12 × 7) / 2 = 84 / 2 = <b>42 cm²</b>'] },
 ],
 video: null,
},

/* ─── Oblast 2: SÍŇ ZLOMKŮ ───────────────────────────────────── */

'2-1': {
 intro: '📜 Písař zlomků střeží svitek. Aby sis ho zasloužil, musíš ovládat zkracování a rozšiřování zlomků.',
 sections: [
  { h: 'Zlomek — připomenutí',
    p: ['Zlomek a/b říká: rozděl celek na b stejných dílů a vezmi si z nich a. Číslo a je čitatel, b je jmenovatel.',
        'Zlomek je definován pro b ≠ 0. Pokud a < b, jde o vlastní zlomek (menší než 1). Pokud a ≥ b, je nevlastní.'] },
  { h: 'Krácení zlomků',
    p: ['Zlomek krátíme, když vydělíme čitatele i jmenovatele stejným číslem větším než 1. Výsledek je rovnocenný zlomek v jednodušším tvaru.',
        'Nejlepší je dělit největším společným dělitelem (NSD) čitatele a jmenovatele.',
        'NSD(12, 18) = 6, takže 12/18 = (12÷6)/(18÷6) = 2/3. Zlomek 2/3 je v základním tvaru (NSD(2,3)=1).'] },
  { h: 'Rozšiřování zlomků',
    p: ['Zlomek rozšíříme, když vynásobíme čitatele i jmenovatele stejným přirozeným číslem. Hodnota zlomku se nemění.',
        '2/5 = (2×3)/(5×3) = 6/15. Nejčastěji rozšiřujeme proto, abychom dostali společný jmenovatel pro součet/rozdíl zlomků.'] },
  { h: 'Jak najít NSD (největší společný dělitel)',
    p: ['Metoda rozkladu na prvočinitele: 12 = 2² × 3, 18 = 2 × 3². NSD = 2¹ × 3¹ = 6.',
        'Nebo Eukleidův algoritmus: NSD(18, 12): 18 = 1 × 12 + 6; 12 = 2 × 6 + 0; NSD = 6.'] },
 ],
 formulas: [
  '<b>Krácení:</b> a/b = (a÷k)/(b÷k), kde k = NSD(a,b)',
  '<b>Rozšiřování:</b> a/b = (a×k)/(b×k) pro libovolné k ≠ 0',
  '<b>Základní tvar:</b> NSD(čitatel, jmenovatel) = 1',
 ],
 examples: [
  { q: 'Zkrať zlomek 24/36 na základní tvar', s: ['NSD(24, 36) = 12', '24/36 = (24÷12)/(36÷12) = <b>2/3</b>'] },
  { q: 'Rozšiř 3/4 na jmenovatele 20', s: ['4 × 5 = 20, takže rozšiřujeme 5×', '3/4 = (3×5)/(4×5) = <b>15/20</b>'] },
 ],
 video: null,
},

'2-2': {
 intro: '🪶 Duch papyru se probouzí! Chce vidět, jak sčítáš a odčítáš zlomky s různými jmenovateli.',
 sections: [
  { h: 'Sčítání a odčítání se stejným jmenovatelem',
    p: ['Je-li jmenovatel stejný, stačí sečíst (nebo odečíst) čitatele: 3/7 + 2/7 = 5/7. Jmenovatel zůstává.',
        'Výsledek vždy zkrať, pokud je to možné: 4/6 = 2/3.'] },
  { h: 'Společný jmenovatel (NSN)',
    p: ['Pro zlomky s různými jmenovateli musíme nejprve najít nejmenší společný násobek (NSN) jmenovatelů — tzv. společný jmenovatel.',
        'NSN(4, 6) = 12. Poté rozšíříme oba zlomky: 1/4 = 3/12 a 1/6 = 2/12.',
        'NSN najdeme rozkladem na prvočinitele: 4 = 2², 6 = 2 × 3; NSN = 2² × 3 = 12.'] },
  { h: 'Postup sčítání',
    p: ['1. Najdi NSN jmenovatelů.',
        '2. Rozšiř každý zlomek na tento jmenovatel.',
        '3. Sečti (odečti) čitatele.',
        '4. Výsledek zkrať na základní tvar.'] },
  { h: 'Smíšená čísla',
    p: ['Smíšené číslo (celá část + zlomek, např. 2 3/4) převeď na nevlastní zlomek: 2 3/4 = (2×4+3)/4 = 11/4. Pak počítej běžně.',
        'Na závěr výsledek klidně převeď zpět na smíšené číslo: 17/5 = 3 2/5 (protože 17 = 3 × 5 + 2).'] },
 ],
 formulas: [
  '<b>Stejný jmenovatel:</b> a/n ± b/n = (a ± b)/n',
  '<b>Různé jmenovatele:</b> a/b ± c/d — rozšiř na NSN(b,d), pak sečti čitatele',
  '<b>Smíšené číslo → zlomek:</b> k a/b = (k·b + a)/b',
 ],
 examples: [
  { q: 'Spočítej: 3/4 + 2/6', s: ['NSN(4, 6) = 12', '3/4 = 9/12, 2/6 = 4/12', '9/12 + 4/12 = 13/12 = <b>1 1/12</b>'] },
  { q: 'Spočítej: 2 1/3 − 5/6', s: ['2 1/3 = 7/3', 'NSN(3, 6) = 6', '7/3 = 14/6', '14/6 − 5/6 = 9/6 = 3/2 = <b>1 1/2</b>'] },
 ],
 video: null,
},

'2-3': {
 intro: '🐍 Had hieroglyfů se plazí — zlomky musíš násobit a dělit. Opatrně, má jedový zub!',
 sections: [
  { h: 'Násobení zlomků',
    p: ['Zlomky násobíme jednoduše: čitatel × čitatel, jmenovatel × jmenovatel.',
        '3/5 × 2/7 = (3×2)/(5×7) = 6/35.',
        'Tip: zkrátit můžeš ještě před násobením — zkrácení „křížem". 3/10 × 5/6 → zkrátíme 3:3 a 6:3, pak 5:5 a 10:5 → 1/2 × 1/2 = 1/4.'] },
  { h: 'Zlomek přirozeného čísla',
    p: ['3/4 z čísla 20 = 3/4 × 20 = (3 × 20)/4 = 60/4 = 15. Nebo: 20 ÷ 4 × 3 = 5 × 3 = 15. Nejprve dělíme jmenovatelem, pak násobíme čitatelem.'] },
  { h: 'Převrácené číslo (reciproká hodnota)',
    p: ['Převrácené číslo k a/b je b/a. Součin čísla a jeho převráceného je vždy 1: a/b × b/a = 1.',
        'Příklady: převrácené k 3/4 je 4/3; k 5 je 1/5; k 2/3 je 3/2.'] },
  { h: 'Dělení zlomků',
    p: ['Dělení zlomkem = násobení převráceným zlomkem.',
        'a/b ÷ c/d = a/b × d/c = (a×d)/(b×c).',
        'Příklad: 3/5 ÷ 2/7 = 3/5 × 7/2 = 21/10 = 2 1/10.'] },
 ],
 formulas: [
  '<b>Násobení:</b> a/b × c/d = (a·c)/(b·d)',
  '<b>Dělení:</b> a/b ÷ c/d = a/b × d/c = (a·d)/(b·c)',
  '<b>Zlomek z čísla:</b> a/b z n = n × a/b = (n·a)/b',
 ],
 examples: [
  { q: 'Spočítej: 4/9 × 3/8', s: ['4/9 × 3/8 — zkrácení křížem: 4:4 a 8:4 → 1/9 × 3/2', 'Ještě: 3:3 a 9:3 → 1/3 × 1/2 = <b>1/6</b>'] },
  { q: 'Spočítej: 5/6 ÷ 10/3', s: ['5/6 × 3/10 = 15/60 = <b>1/4</b>'] },
 ],
 video: null,
},

/* ─── Oblast 3: PODZEMNÍ MRAZÍRNA ─────────────────────────────── */

'3-1': {
 intro: '❄️ Ledový strážce křičí: „Záporná čísla tě zmrazí, pokud je neovládáš!"',
 sections: [
  { h: 'Celá čísla a číselná osa',
    p: ['Celá čísla ℤ = {…, −3, −2, −1, 0, 1, 2, 3, …}. Záporná čísla jsou vlevo od nuly, kladná vpravo.',
        'Čím víc vlevo, tím menší číslo: −5 < −2 < 0 < 3. Opačné číslo k a je −a; číslo opačné k −5 je 5.'] },
  { h: 'Sčítání celých čísel',
    p: ['Kladné + kladné: normálně. (+3) + (+5) = +8.',
        'Záporné + záporné: sečteš absolutní hodnoty a přidáš −. (−3) + (−5) = −8.',
        'Kladné + záporné (nebo opačně): od většího (absolutní hodnotou) odečteš menší, znaménko přebere větší číslo.',
        '(+7) + (−3) = +(7−3) = +4; (+3) + (−7) = −(7−3) = −4.'] },
  { h: 'Odčítání celých čísel',
    p: ['Odečíst číslo = přičíst číslo opačné! a − b = a + (−b).',
        '5 − (−3) = 5 + 3 = 8. Dvě minusová znaménka za sebou se mění v plus.',
        '−4 − (−6) = −4 + 6 = 2.',
        'Pravidlo: „minus minus = plus", „minus plus = minus".'] },
 ],
 formulas: [
  '<b>a − (−b) = a + b</b>',
  '<b>(−a) + (−b) = −(a + b)</b>',
  '<b>|a|</b> = absolutní hodnota (vzdálenost od nuly, vždy ≥ 0)',
 ],
 examples: [
  { q: 'Spočítej: (−8) + (+5)', s: ['|−8| = 8 > |+5| = 5, znaménko: minus', '(−8) + (+5) = <b>−3</b>'] },
  { q: 'Spočítej: 3 − (−7)', s: ['3 − (−7) = 3 + 7 = <b>10</b>'] },
  { q: 'Spočítej: (−4) − (−9)', s: ['(−4) − (−9) = −4 + 9 = <b>5</b>'] },
 ],
 video: null,
},

'3-2': {
 intro: '🧊 Krystalový golem tě zasype ledem! Pravidla znamének při násobení a dělení ti ho porazí.',
 sections: [
  { h: 'Násobení celých čísel — pravidla znamének',
    p: ['(+) × (+) = (+):  3 × 4 = 12',
        '(−) × (−) = (+): (−3) × (−4) = 12',
        '(+) × (−) = (−):  3 × (−4) = −12',
        '(−) × (+) = (−): (−3) × 4 = −12',
        'Jednoduché pravidlo: Lichý počet záporných čísel → záporný výsledek. Sudý počet → kladný výsledek.'] },
  { h: 'Dělení celých čísel',
    p: ['Stejná pravidla jako u násobení: (+)÷(+) = +, (−)÷(−) = +, (+)÷(−) = −, (−)÷(+) = −.',
        '(−12) ÷ (−3) = 4 (obě záporné → kladný výsledek).',
        '(−12) ÷ (+3) = −4 (různá znaménka → záporný výsledek).'] },
  { h: 'Mocniny záporných čísel',
    p: ['(−2)² = (−2) × (−2) = 4 (sudá mocnina záporného čísla → kladná).',
        '(−2)³ = (−2) × (−2) × (−2) = −8 (lichá mocnina záporného čísla → záporná).',
        'Pozor na závorky! −2² = −(2²) = −4, ale (−2)² = 4. Závorky mění vše!'] },
 ],
 formulas: [
  '<b>(+) × (+) = (+)</b>',
  '<b>(−) × (−) = (+)</b>',
  '<b>(+) × (−) = (−)</b>',
  '<b>(−a)² = a²</b> (sudá mocnina)',
  '<b>(−a)³ = −a³</b> (lichá mocnina)',
 ],
 examples: [
  { q: 'Spočítej: (−5) × (−8)', s: ['obě záporná → kladný výsledek', '5 × 8 = 40 → <b>+40</b>'] },
  { q: 'Spočítej: (−36) ÷ (+4)', s: ['různá znaménka → záporný výsledek', '36 ÷ 4 = 9 → <b>−9</b>'] },
  { q: 'Spočítej: (−3)⁴', s: ['sudá mocnina záporného čísla → kladná', '3⁴ = 81 → <b>+81</b>'] },
 ],
 video: null,
},

'3-3': {
 intro: '🌀 Vír mrazu tě pohlcuje! Zachrání tě jen racionální čísla — čísla, která se dají zapsat jako zlomek.',
 sections: [
  { h: 'Racionální čísla',
    p: ['Racionální čísla ℚ jsou všechna čísla, která lze zapsat ve tvaru p/q, kde p ∈ ℤ a q ∈ ℤ, q ≠ 0.',
        'Do ℚ patří: celá čísla (5 = 5/1), zlomky (3/4), záporné zlomky (−2/5), desetinná čísla (0,3 = 3/10), periodická desetinná čísla (0,333... = 1/3).'] },
  { h: 'Racionální čísla na číselné ose',
    p: ['Každé racionální číslo má přesné místo na číselné ose. Záporné zlomky jsou vlevo od nuly.',
        'Porovnávání: −1/2 > −3/4, protože na číselné ose je −1/2 napravo od −3/4 (blíže k nule).',
        'Jak porovnat dva záporné zlomky? Převeď na stejný jmenovatel: −1/2 = −2/4, −3/4 = −3/4. Protože −2 > −3, platí −2/4 > −3/4.'] },
  { h: 'Absolutní hodnota',
    p: ['Absolutní hodnota |a| je vzdálenost čísla a od nuly na číselné ose. Vždy nezáporná.',
        '|−5| = 5, |3| = 3, |0| = 0, |−2/3| = 2/3.',
        'Platí: |a| = a pro a ≥ 0; |a| = −a pro a < 0 (výsledek je kladný!).'] },
  { h: 'Operace s racionálními čísly',
    p: ['Kombinuješ pravidla pro zlomky A pravidla pro celá čísla (znaménka).',
        '(−3/4) + (1/2) = (−3/4) + (2/4) = −1/4.',
        '(−2/3) × (−3/5) = +(2×3)/(3×5) = 6/15 = 2/5.'] },
 ],
 formulas: [
  '<b>ℚ = {p/q | p ∈ ℤ, q ∈ ℤ, q ≠ 0}</b>',
  '<b>|a| ≥ 0</b> pro každé a',
  '<b>|a × b| = |a| × |b|</b>',
 ],
 examples: [
  { q: 'Porovnej: −3/5 a −1/2', s: ['NSN(5, 2) = 10', '−3/5 = −6/10, −1/2 = −5/10', 'Protože −6 < −5, platí <b>−3/5 < −1/2</b>'] },
  { q: 'Spočítej: (−2/3) × (−9/4)', s: ['(−) × (−) = (+)', '(2×9)/(3×4) = 18/12 = <b>3/2 = 1,5</b>'] },
 ],
 video: null,
},

/* ─── Oblast 4: VÁŽNICE POMĚRŮ ────────────────────────────────── */

'4-1': {
 intro: '⚖️ Strážce vah potřebuje znát poměr. Bez znalosti poměrů z vážnice nevyjdeš.',
 sections: [
  { h: 'Co je poměr?',
    p: ['Poměr a : b (čteme „a ku b") vyjadřuje, kolikrát je jedno číslo větší než druhé — nebo přesněji, jaká je jejich vzájemná relace.',
        'Poměr 3 : 5 říká, že na každé 3 díly prvního připadá 5 dílů druhého. Poměr není zlomek, ale úzce s ním souvisí: 3 : 5 odpovídá zlomku 3/5.'] },
  { h: 'Zjednodušování poměru',
    p: ['Poměr zjednodušujeme stejně jako zlomek — dělíme oba členy NSD.',
        '12 : 18 = (12÷6) : (18÷6) = 2 : 3.',
        'Poměr může mít i více členů: 6 : 9 : 15 → NSD(6,9,15) = 3 → 2 : 3 : 5.'] },
  { h: 'Dělení celku v poměru',
    p: ['Celek C rozdělit v poměru a : b : c znamená: spočítej celkový počet dílů (a+b+c), pak každé části přiřaď odpovídající počet dílů.',
        'Příklad: 240 Kč v poměru 1 : 2 : 3. Celkem 6 dílů. 1 díl = 240 ÷ 6 = 40 Kč.',
        'Části: 40 Kč, 80 Kč, 120 Kč. Kontrola: 40 + 80 + 120 = 240 ✓'] },
  { h: 'Poměr v praxi',
    p: ['Recept: na 4 porce potřebuješ 300 g mouky. Na 6 porcí? Poměr porcí 4 : 6 = 2 : 3. Mouka: 300 × 3/2 = 450 g.',
        'Měřítko: mapa 1 : 50 000 znamená 1 cm na mapě = 50 000 cm = 500 m ve skutečnosti.'] },
 ],
 formulas: [
  '<b>a : b = (a÷k) : (b÷k)</b>, kde k = NSD(a, b)',
  '<b>Díl při dělení v poměru a:b:</b> 1 díl = C / (a + b)',
  '<b>Části:</b> a/(a+b) × C a b/(a+b) × C',
 ],
 examples: [
  { q: 'Zjednoduš poměr 36 : 48', s: ['NSD(36, 48) = 12', '36:48 = (36÷12):(48÷12) = <b>3 : 4</b>'] },
  { q: 'Rozděl 180 cm v poměru 2 : 3 : 4', s: ['Celkem dílů: 2+3+4 = 9', '1 díl = 180 ÷ 9 = 20 cm', 'Části: <b>40 cm, 60 cm, 80 cm</b>', 'Kontrola: 40+60+80 = 180 ✓'] },
 ],
 video: null,
},

'4-2': {
 intro: '🐪 Pán karavany potřebuje vědět, za jak dlouho dorazí. Trojčlenka a úměrnosti ho dovedou cíle.',
 sections: [
  { h: 'Přímá úměrnost',
    p: ['Dvě veličiny jsou přímo úměrné, pokud se jejich poměr nemění: y/x = k (konstanta úměrnosti).',
        'Jinými slovy: jak se zvětší x, tak se zvětší y. Cena za 3 kg = 90 Kč → cena za 1 kg = 30 Kč (konstanta k = 30 Kč/kg).',
        'Graf přímé úměrnosti je přímka procházející počátkem.'] },
  { h: 'Nepřímá úměrnost',
    p: ['Dvě veličiny jsou nepřímo úměrné, pokud jejich součin je konstantní: x × y = k.',
        'Jinými slovy: jak se zvětší x, tak se zmenší y. Více pracovníků → kratší čas. 3 dělníci dokončí práci za 8 dní → 1 dělník za 24 dní, 6 dělníků za 4 dny.',
        'Graf nepřímé úměrnosti je hyperbola.'] },
  { h: 'Trojčlenka — postup',
    p: ['Trojčlenka je postup, jak řešit úlohy o přímé/nepřímé úměrnosti.',
        'Přímá: 5 kg stojí 150 Kč. Kolik stojí 8 kg?',
        '5 kg … 150 Kč; 1 kg … 150÷5 = 30 Kč; 8 kg … 30×8 = 240 Kč.',
        'Nepřímá: 4 koně sežerou zásobu za 12 dní. Za jak dlouho 6 koní?',
        '4 koně … 12 dní; 1 kůň … 4×12 = 48 dní; 6 koní … 48÷6 = 8 dní.'] },
 ],
 formulas: [
  '<b>Přímá úměrnost:</b> y₁/x₁ = y₂/x₂ (nebo y = k·x)',
  '<b>Nepřímá úměrnost:</b> x₁·y₁ = x₂·y₂ (nebo y = k/x)',
 ],
 examples: [
  { q: 'Za 3 hodiny ujede vlak 210 km. Kolik ujede za 5 hodin? (přímá úměrnost)', s: ['1 hod … 210÷3 = 70 km', '5 hod … 70×5 = <b>350 km</b>'] },
  { q: '6 dělníků postaví zeď za 4 dny. Za kolik dní to zvládnou 3 dělníci? (nepřímá)', s: ['6 × 4 = 24 (celkem dní práce)', '3 dělníci … 24÷3 = <b>8 dní</b>'] },
 ],
 video: null,
},

'4-3': {
 intro: '🗺️ Kartograf potřebuje tvou pomoc. Musíš přepočítat vzdálenosti z mapy na skutečnost.',
 sections: [
  { h: 'Co je měřítko mapy?',
    p: ['Měřítko mapy vyjadřuje poměr délky na mapě k délce ve skutečnosti.',
        'Měřítko 1 : 50 000 říká: 1 cm na mapě odpovídá 50 000 cm = 500 m = 0,5 km ve skutečnosti.',
        'Měřítko 1 : 5000 je podrobnější (větší měřítko) než 1 : 100 000.'] },
  { h: 'Přepočet vzdáleností',
    p: ['Skutečná vzdálenost = vzdálenost na mapě × měřítko.',
        'Vzdálenost na mapě = skutečná vzdálenost ÷ měřítko.',
        'Příklad (1 : 25 000): Změříme 4 cm na mapě → skutečně 4 × 25 000 = 100 000 cm = 1 km.'] },
  { h: 'Přepočet ploch',
    p: ['Při přepočtu obsahu musíme použít ČTVEREC měřítka! Pokud je měřítko 1 : 1000, pak 1 cm² na plánu odpovídá 1000² cm² = 1 000 000 cm² = 100 m² ve skutečnosti.',
        'Obecně: skutečný obsah = obsah na mapě × (měřítko)².'] },
 ],
 formulas: [
  '<b>d_skut = d_mapa × M</b>  (M = měřítko, číslo za 1:)',
  '<b>d_mapa = d_skut ÷ M</b>',
  '<b>S_skut = S_mapa × M²</b>  (pro plochy)',
 ],
 examples: [
  { q: 'Na mapě 1 : 20 000 měříme 6,5 cm. Jak dlouhá je cesta ve skutečnosti?', s: ['d = 6,5 cm × 20 000 = 130 000 cm = <b>1,3 km</b>'] },
  { q: 'Na plánu 1 : 500 má park obsah 4 cm². Jaký je skutečný obsah?', s: ['S = 4 × 500² = 4 × 250 000 = 1 000 000 cm² = <b>100 m²</b>'] },
 ],
 video: null,
},

/* ─── Oblast 5: ZLATÁ POKLADNICE ──────────────────────────────── */

'5-1': {
 intro: '🪙 Hlídač mincí střeží zlaté procento. Bez pochopení procentové části tě sem nepustí.',
 sections: [
  { h: 'Co je procento?',
    p: ['Procento (%) je setina celku. 1 % = 1/100. Říkáme tedy: „X procent z celku C" = X/100 × C.',
        '100 % celku = celý základ. 50 % = polovina. 1 % = jedna setina.'] },
  { h: 'Procentová část z',
    p: ['Procentová část z je ta část základu, kterou hledáme.',
        'z = p% z C = p/100 × C = C × p : 100.',
        'Příklad: Kolik je 15 % z 240? z = 240 × 15/100 = 240 × 0,15 = 36.'] },
  { h: 'Trojúhelník procent',
    p: ['Pro práci s procenty si zapamatuj trojúhelník: nahoře z (část), dole vlevo C (základ/celek), dole vpravo p (počet procent).',
        'Zakryješ to, co hledáš: zakryj z → z = C × p/100; zakryj C → C = z/(p/100) = z×100/p; zakryj p → p = z/C × 100.'] },
  { h: 'Praktické tipy',
    p: ['1 % ze 400 = 4. Z toho si odvoď cokoli: 5 % = 5 × 4 = 20; 15 % = 15 × 4 = 60.',
        '10 % je vždy snadné — stačí vydělit 10. 5 % = polovina z 10 %. 1 % = desetina z 10 %.'] },
 ],
 formulas: [
  '<b>z = C × p / 100</b>  (procentová část)',
  '<b>C = z × 100 / p</b>  (základ)',
  '<b>p = z / C × 100</b>  (počet procent)',
 ],
 examples: [
  { q: 'Kolik je 25 % z 360?', s: ['z = 360 × 25/100 = 360 × 0,25 = <b>90</b>'] },
  { q: 'DPH (21 %) z ceny 1200 Kč je kolik?', s: ['z = 1200 × 21/100 = 12 × 21 = <b>252 Kč</b>'] },
 ],
 video: null,
},

'5-2': {
 intro: '⚱️ Strážce urny tě vyzkouší: dokážeš najít základ nebo počet procent?',
 sections: [
  { h: 'Počet procent p',
    p: ['Máme základ C a část z, hledáme kolik procent z tvoří z C.',
        'p = z/C × 100.',
        'Příklad: Ze 40 studentů udělalo test 28. Kolik procent? p = 28/40 × 100 = 0,7 × 100 = 70 %.'] },
  { h: 'Základ C',
    p: ['Víme, že z tvoří p %, hledáme, z čeho (základ C).',
        'C = z × 100 / p.',
        'Příklad: 36 Kč je 12 % z čeho? C = 36 × 100 / 12 = 3600 / 12 = 300 Kč.'] },
  { h: 'Procentové zvýšení a snížení',
    p: ['Zvýšení o p %: nová hodnota = C × (1 + p/100) = C + z.',
        'Snížení o p %: nová hodnota = C × (1 − p/100) = C − z.',
        'Cena 500 Kč zlevněna o 20 %: nová cena = 500 × 0,80 = 400 Kč.',
        'Cena 500 Kč zdražena o 10 %: nová cena = 500 × 1,10 = 550 Kč.'] },
 ],
 formulas: [
  '<b>p = z/C × 100</b>  (počet procent)',
  '<b>C = z × 100 / p</b>  (základ)',
  '<b>Zvýšení o p %:</b> nová = C × (1 + p/100)',
  '<b>Snížení o p %:</b> nová = C × (1 − p/100)',
 ],
 examples: [
  { q: 'Ze 150 žáků dostalo jedničku 45. Kolik procent?', s: ['p = 45/150 × 100 = 0,3 × 100 = <b>30 %</b>'] },
  { q: '48 Kč je 16 % z jaké ceny?', s: ['C = 48 × 100 / 16 = 4800 / 16 = <b>300 Kč</b>'] },
 ],
 video: null,
},

'5-3': {
 intro: '👑 Pokladník faraona ti zadá záludné slovní úlohy s procenty. Sleva, zdražení, daň — vše musíš umět.',
 sections: [
  { h: 'Sleva',
    p: ['Sleva = procentová část ze základní ceny. Nová cena = základní cena − sleva.',
        'Nebo přímo: nová cena = základ × (1 − sleva%/100).',
        'Příklad: Mikina stojí 600 Kč, sleva 30 %. Nová cena: 600 × 0,70 = 420 Kč.'] },
  { h: 'DPH (daň z přidané hodnoty)',
    p: ['Cena bez DPH × (1 + DPH/100) = cena s DPH.',
        'Cena s DPH ÷ (1 + DPH/100) = cena bez DPH.',
        'Příklad: základní sazba DPH v ČR je 21 %. Zboží stojí 300 Kč bez DPH → s DPH: 300 × 1,21 = 363 Kč.'] },
  { h: 'Procento z procenta, zpětný výpočet',
    p: ['Po slevě 20 % vyjde 320 Kč. Jaká byla původní cena?',
        '320 Kč = 80 % původní ceny. C = 320 × 100/80 = 400 Kč.',
        'Zlomky procent: 12,5 % = 1/8. 12,5 % z 240 = 240/8 = 30.'] },
  { h: 'Složené úroky (bonusové)',
    p: ['Spoření: každý rok se základ zvýší o p %. Po n letech: hodnota = C × (1 + p/100)ⁿ.',
        '1000 Kč při 3 % ročním úroku po 2 letech: 1000 × 1,03² = 1000 × 1,0609 = 1060,90 Kč.'] },
 ],
 formulas: [
  '<b>Cena po slevě p %:</b> C_nová = C × (1 − p/100)',
  '<b>Cena s DPH:</b> C_DPH = C_bez × (1 + DPH/100)',
  '<b>Zpětný výpočet:</b> C_základ = hodnota_po_slevě / (1 − p/100)',
 ],
 examples: [
  { q: 'Kniha stojí původně 250 Kč, je o 12 % levnější. Kolik stojí?', s: ['Cena po slevě = 250 × (1 − 0,12) = 250 × 0,88 = <b>220 Kč</b>'] },
  { q: 'Po zdražení o 25 % stojí výrobek 500 Kč. Kolik stál původně?', s: ['500 = C × 1,25', 'C = 500 / 1,25 = <b>400 Kč</b>'] },
 ],
 video: null,
},

/* ─── Oblast 6: ZRCADLOVÁ SVATYNĚ ─────────────────────────────── */

'6-1': {
 intro: '🪞 Strážce zrcadla tě vyzve: „Najdi obraz každého bodu." Osová souměrnost ovládá tuto místnost.',
 sections: [
  { h: 'Osová souměrnost — co to je?',
    p: ['Osová souměrnost je geometrické zobrazení: každý bod X zobrazíme na bod X\' tak, aby osa souměrnosti o byla osou úsečky XX\'.',
        'To znamená: osa o prochází středem XX\' a je na XX\' kolmá.'] },
  { h: 'Jak sestrojit obraz bodu',
    p: ['1. Z bodu X sestrojíme kolmici k ose o.',
        '2. Kolmice protne osu o v bodě S (střed).',
        '3. Bod X\' leží na kolmici na opačné straně, ve vzdálenosti XS = SX\'.',
        'Zkratka: zrcadlíme bod přes osu — obraz je stejně daleko od osy, ale na druhé straně.'] },
  { h: 'Vlastnosti osové souměrnosti',
    p: ['Zobrazení zachovává vzdálenosti i úhly (jedná se o shodné zobrazení).',
        'Obraz přímky kolmé na osu je tatáž přímka. Obraz přímky rovnoběžné s osou je přímka na opačné straně ve stejné vzdálenosti.',
        'Obrazec je souměrný podle osy, pokud se zobrazí sám na sebe.'] },
  { h: 'Kde se setkáme s osovou souměrností',
    p: ['Tvary s osou souměrnosti: čtverec (4 osy), obdélník (2 osy), rovnoramenný trojúhelník (1 osa), kružnice (nekonečně mnoho os), písmena A, M, T, V, …'] },
 ],
 formulas: [
  '<b>Obraz bodu X přes osu o:</b> o je osa úsečky XX\' (kolmice v středu)',
  '<b>|XS| = |SX\'|</b>, kde S = průsečík XX\' s osou o',
 ],
 examples: [
  { q: 'Bod A[2, 1] zobrazíme v osové souměrnosti přes osu y. Najdi obraz A\'.', s: ['Osa y: x = 0. Zrcadlíme x-souřadnici: x → −x', 'A\'[−2, 1]'] },
  { q: 'Bod B[3, −2] zobrazíme přes osu x = 1. Najdi B\'.', s: ['Vzdálenost B od osy: 3 − 1 = 2', 'B\' je na druhé straně: x\' = 1 − 2 = −1', 'B\'[−1, −2]'] },
 ],
 video: null,
},

'6-2': {
 intro: '🌗 Duch středu říká: „Každý bod má svůj pár přes střed souměrnosti." Pochop středovou souměrnost!',
 sections: [
  { h: 'Středová souměrnost',
    p: ['Středová souměrnost zobrazí bod X na bod X\' tak, aby střed souměrnosti S byl středem úsečky XX\'.',
        'To je ekvivalentní otočení o 180° kolem bodu S.'] },
  { h: 'Jak sestrojit obraz bodu',
    p: ['1. Spojíme bod X se středem S.',
        '2. Prodloužíme úsečku XS za S o stejnou vzdálenost.',
        '3. Takto dostaneme X\'.',
        'Nebo: X\' = 2S − X (souřadnicově).'] },
  { h: 'Středová souměrnost v souřadnicové soustavě',
    p: ['Zobrazení středem O[0, 0]: bod [x, y] → [−x, −y].',
        'Zobrazení středem S[a, b]: bod [x, y] → [2a − x, 2b − y].'] },
  { h: 'Porovnání s osovou souměrností',
    p: ['Osová: obraz je zrcadlový (levá/pravá ruka se zamění). Středová: obraz je otočen, není zrcadlový.',
        'Tvary středově souměrné: kružnice, čtverec, obdélník, rovnoběžník, písmena S, Z, N, …'] },
 ],
 formulas: [
  '<b>Obraz bodu X přes střed S:</b> X\' = 2S − X',
  '<b>Střed souměrnosti S = střed úsečky XX\'</b>',
 ],
 examples: [
  { q: 'Bod A[3, 5] zobrazíme středovou souměrností přes střed O[0, 0]. Najdi A\'.', s: ['A\' = [−3, −5]'] },
  { q: 'Bod B[1, 2] zobrazíme přes střed S[3, 4]. Najdi B\'.', s: ['x\' = 2×3 − 1 = 5, y\' = 2×4 − 2 = 6', 'B\'[5, 6]'] },
 ],
 video: null,
},

'6-3': {
 intro: '🔺 Kněz shodnosti tě vyzkouší na věty o shodnosti trojúhelníků. Zvládneš je všechny?',
 sections: [
  { h: 'Shodnost trojúhelníků',
    p: ['Dva trojúhelníky jsou shodné, pokud se jeden dá na druhý překrýt (posuvem, otočením nebo převrácením).',
        'Tedy mají stejné délky všech stran a stejné velikosti všech úhlů.'] },
  { h: 'Věty o shodnosti (kritéria)',
    p: ['Ke shodnosti NESTAČÍ zkontrolovat všech 6 prvků — stačí 3 správně zvolené.',
        '<b>Věta sss:</b> shodují-li se trojúhelníky ve všech třech stranách.',
        '<b>Věta sus:</b> shodují-li se ve dvou stranách a úhlu jimi sevřeném.',
        '<b>Věta usu:</b> shodují-li se v jedné straně a dvou přilehlých úhlech (tedy celkově ví mě všechno).',
        '<b>Věta Suu:</b> shodují-li se v jedné straně, úhlu přilehlém a úhlu odlehlém (platí pro pravoúhlé trojúhelníky jako přepona + úhel).'] },
  { h: 'Jak dokázat shodnost v úloze',
    p: ['1. Pojmenuj trojúhelníky a jejich vrcholy.',
        '2. Urči, která strany/úhly jsou si rovny (z předpokladů, ze symetrie, z parallely…).',
        '3. Cituj příslušnou větu (sss / sus / usu).',
        '4. Napiš závěr: △ABC ≅ △DEF (pořadí vrcholů odpovídá si navzájem).'] },
 ],
 formulas: [
  '<b>Věta sss:</b> a = a\', b = b\', c = c\' → △ ≅ △\'',
  '<b>Věta sus:</b> a = a\', β = β\', c = c\' → △ ≅ △\'',
  '<b>Věta usu:</b> a = a\', α = α\', β = β\' → △ ≅ △\'',
 ],
 examples: [
  { q: 'Které věty bychom použili: △ABC, kde a=5 cm, b=7 cm, c=9 cm; △DEF, kde d=5, e=7, f=9?', s: ['Shodují se všechny tři strany → <b>věta sss</b> → △ABC ≅ △DEF'] },
  { q: 'AB = DE, AC = DF, úhel A = úhel D. Která věta?', s: ['Dvě strany a úhel jimi sevřený → <b>věta sus</b>'] },
 ],
 video: null,
},

/* ─── Oblast 7: VELKÁ PYRAMIDA ─────────────────────────────────── */

'7-1': {
 intro: '🟫 Dlaždič pyramidy pokládá čtyřúhelníkové dlaždice. Musíš spočítat jejich obsah!',
 sections: [
  { h: 'Rovnoběžník',
    p: ['Rovnoběžník má dvě dvojice rovnoběžných stran. Obsah S = a × h, kde a je délka základny a h je výška (kolmá vzdálenost rovnoběžných stran).',
        'Pozor: výška h NENÍ délka boční strany, ale kolmice z vrcholu na základnu (nebo její prodloužení).'] },
  { h: 'Kosočtverec (rhombus)',
    p: ['Kosočtverec je rovnoběžník s rovnými stranami. Obsah lze spočítat jako S = (d₁ × d₂) / 2, kde d₁ a d₂ jsou délky úhlopříček.',
        'Také S = a × h (jako rovnoběžník).'] },
  { h: 'Lichoběžník',
    p: ['Lichoběžník má jednu dvojici rovnoběžných stran (základny a, c; ostatní dvě strany jsou ramena).',
        'Obsah S = (a + c) / 2 × h, kde h je výška (kolmá vzdálenost základen).'] },
  { h: 'Obecný čtyřúhelník',
    p: ['Rozdělíme úhlopříčkou na dva trojúhelníky a spočítáme jejich obsahy zvlášť.',
        'Nebo: S = (d × h₁ + d × h₂) / 2 = d × (h₁ + h₂) / 2, kde d je úhlopříčka a h₁, h₂ jsou výšky obou trojúhelníků na ni.'] },
 ],
 formulas: [
  '<b>Rovnoběžník:</b> S = a · h',
  '<b>Kosočtverec:</b> S = d₁ · d₂ / 2',
  '<b>Lichoběžník:</b> S = (a + c) / 2 · h',
 ],
 examples: [
  { q: 'Rovnoběžník má základnu 8 cm a výšku 5 cm. Jaký je obsah?', s: ['S = 8 × 5 = <b>40 cm²</b>'] },
  { q: 'Lichoběžník: základny 6 cm a 10 cm, výška 4 cm. Obsah?', s: ['S = (6 + 10)/2 × 4 = 8 × 4 = <b>32 cm²</b>'] },
  { q: 'Kosočtverec s úhlopříčkami 12 cm a 7 cm. Obsah?', s: ['S = 12 × 7 / 2 = 84/2 = <b>42 cm²</b>'] },
 ],
 video: null,
},

'7-2': {
 intro: '📦 Strážce hrobky ohlídá kvádr. Musíš spočítat povrch i objem — jinak tě zamkne uvnitř!',
 sections: [
  { h: 'Hranol — definice',
    p: ['Hranol je geometrické těleso, jehož dvě podstavy jsou shodné a rovnoběžné mnohostěny (trojúhelník, čtyřúhelník, šestiúhelník…). Boční stěny jsou obdélníky.',
        'Nejčastěji řešíme kvádr (obdélníkový hranol) a trojboký hranol.'] },
  { h: 'Kvádr (obdélníkový hranol)',
    p: ['Kvádr má strany a, b, c. Objem V = a × b × c. Povrch S = 2(ab + bc + ac).',
        'Povrch = součet ploch všech 6 stěn: 2× (a×b) + 2× (b×c) + 2× (a×c).'] },
  { h: 'Trojboký hranol',
    p: ['Podstava je trojúhelník s obsahem S_p. Výška hranolu je h.',
        'Objem V = S_p × h.',
        'Povrch = 2 × S_p + obvod_podstavy × h (celý plášť = 3 obdélníky).'] },
  { h: 'Obecný hranol',
    p: ['Objem = obsah podstavy × výška: V = S_p × h.',
        'Povrch = 2 × S_p + plášť. Plášť = obvod podstavy × výška (pro přímý hranol).'] },
 ],
 formulas: [
  '<b>Objem hranolu:</b> V = S_p · h',
  '<b>Povrch kvádru:</b> S = 2(ab + bc + ac)',
  '<b>Povrch hranolu:</b> S = 2·S_p + o·h  (o = obvod podstavy)',
 ],
 examples: [
  { q: 'Kvádr: a = 5 cm, b = 4 cm, c = 3 cm. Objem a povrch?', s: ['V = 5 × 4 × 3 = <b>60 cm³</b>', 'S = 2(5×4 + 4×3 + 5×3) = 2(20+12+15) = 2×47 = <b>94 cm²</b>'] },
  { q: 'Hranol s pravoúhlou trojúhelníkovou podstavou (odvěsny 3 a 4 cm) a výškou 10 cm. Objem?', s: ['S_p = (3 × 4)/2 = 6 cm²', 'V = 6 × 10 = <b>60 cm³</b>'] },
 ],
 video: null,
},

'7-3': {
 intro: '🗿 Strážce pyramidy — finální boss! Prověří tě ze všech témat 7. ročníku. Jsi připraven?',
 sections: [
  { h: 'Přehled témat 7. ročníku',
    p: ['Tento úkol je shrnutím všeho, co sis prošel v Ztracenému chrámu. Připomeň si klíčové vzorce a postupy.'] },
  { h: 'Oblast 1: Čísla',
    p: ['Desetinná čísla: sčítání/odčítání (zarovnej čárky), násobení (sečti des. místa), dělení (odstraň des. ze jmenovatele).',
        'Obvod a obsah: čtverec (4a, a²), obdélník (2(a+b), ab), trojúhelník (a+b+c, ah/2), rovnoběžník (ah).'] },
  { h: 'Oblast 2–3: Zlomky a celá čísla',
    p: ['Zlomky: krácení (NSD), rozšiřování, sčítání (NSN), násobení (čitatel×čitatel, jmenovatel×jmenovatel), dělení = násobení převráceným.',
        'Celá čísla: pravidla znamének. (−)×(−) = (+). Absolutní hodnota. Racionální čísla ℚ.'] },
  { h: 'Oblast 4–5: Poměr, trojčlenka, procenta',
    p: ['Poměr: zjednodušit (NSD), rozdělit celek. Trojčlenka: přímá (y = kx), nepřímá (xy = k).',
        'Procenta: z = C × p/100; p = z/C × 100; C = z×100/p. Zvýšení/snížení o p %.'] },
  { h: 'Oblast 6–7: Geometrie',
    p: ['Souměrnosti: osová (osa = osa úsečky bodů), středová (střed = střed úsečky bodů).',
        'Shodnost: věty sss, sus, usu.',
        'Obsahy: rovnoběžník (ah), kosočtverec (d₁d₂/2), lichoběžník ((a+c)/2 × h).',
        'Hranol: objem = S_p × h, povrch = 2S_p + o×h.'] },
 ],
 formulas: [
  '<b>Rychlý přehled — viz každá oblast výše</b>',
 ],
 examples: [
  { q: 'Jak se počítá obsah lichoběžníku?', s: ['S = (a + c) / 2 × h, kde a, c jsou základny a h je výška'] },
  { q: 'Kolik je 15 % z 240?', s: ['z = 240 × 15/100 = 36'] },
 ],
 video: null,
},

};
})();
