/* ══════════════════════════════════════════════════════════════════
   RPG Matematika 7 — Teorie ke všem 21 misím (Ztracený chrám ⛏️)
   7. ročník ZŠ, RVP ZV — Odvárko/Kadleček, Hejný (Fraus), MŠMT
   Improved edition: SVG diagrams, deeper examples, Czech conventions
   ══════════════════════════════════════════════════════════════════ */
(function(){
'use strict';
window.RPG_LEARN_7 = {

/* ─── Oblast 1: VSTUPNÍ BRÁNA ─────────────────────────────────── */

'1-1': {
 mistakes: [
  {wrong:'47 × 98 mi vyšlo 460 a beru to', right:'47 × 98 = 4 606', why:'Odhad 50 × 100 = 5 000 ukazuje řád tisíců. 460 je 10× menší — takový rozdíl od odhadu znamená chybu (posunutý řád).'},
  {wrong:'8 × 7 = 8 × 5 + 2 = 42', right:'8 × 5 + 8 × 2 = 40 + 16 = 56', why:'Při rozkladu se OBĚ části násobí osmi (distributivnost), druhá se jen nepřičte.'},
  {wrong:'360 : 8 přes 360 : 4 : 2 = 40', right:'360 : 4 = 90, pak 90 : 2 = 45', why:'Rozklad 360 : 4 : 2 je správná metoda, jen pozor na aritmetiku: 360 : 4 = 90 (ne 20), potom 90 : 2 = 45.'},
 ],
 intro: '⛏️ Strážce karavany tě testuje u brány chrámu: „Kdo neumí počítat zpaměti, dovnitř nevejde." Zopakuj si mentální triky a projdi branou!',
 sections: [
  { h: 'Proč počítat zpaměti?',
    p: ['Výpočty zpaměti šetří čas u testů a v reálném životě. Ale hlavně: <b>odhad ti odhalí hrubé chyby</b> dřív, než je odevzdáš.',
        'Příklad: 47 × 98. Rychlý odhad: 50 × 100 = 5 000. Pokud ti vyjde 460, okamžitě víš, že je to o 10× méně — chyba jinde.',
        'Klíče: znát násobilku do 10 × 10, využívat vlastnosti operací (komutativnost, asociativnost, distributivnost).'] },
  { h: 'Sčítání a odčítání zpaměti',
    p: ['<b>Rozklad na desítky:</b> 47 + 38 = 40 + 30 + 7 + 8 = 70 + 15 = <b>85</b>.',
        '<b>Trik „přidej a odečti":</b> 93 − 47 → odečti 50, přidej 3 → 43 + 3 = 46.',
        '<b>Doplňování do 100:</b> 63 + ? = 100. Postup: 63 → 70 (+7) → 100 (+30) → dohromady 37.'] },
  { h: 'Násobení a dělení zpaměti',
    p: ['<b>Rozklad násobence:</b> 8 × 7 = 8 × 5 + 8 × 2 = 40 + 16 = <b>56</b>.',
        '<b>Násobení číslem 25:</b> 36 × 25 = 36 × 100 : 4 = 3 600 : 4 = <b>900</b>.',
        '<b>Rozklad dělení:</b> 360 : 8 = 360 : 4 : 2 = 90 : 2 = <b>45</b>.'] },
  { h: 'Odhadování — záchranná síť',
    p: ['Před každým výpočtem si polož otázku: <i>„Jaký řád by měl mít výsledek?"</i>',
        '47 × 98 ≈ 50 × 100 = 5 000. Přesný výsledek je 4 606 — odhad potvrdil, že jsme ve správném řádu.',
        '<b>Pravidlo:</b> pokud se výsledek liší od odhadu o více než 2×, hledej chybu.'] },
 ],
 formulas: [
  '<b>a + b = b + a</b> (komutativnost sčítání)',
  '<b>a × b = b × a</b> (komutativnost násobení)',
  '<b>a × (b + c) = a·b + a·c</b> (distributivnost — základ rozkladů)',
  '<b>(a + b) − c = a + (b − c)</b>',
 ],
 examples: [
  { q: 'Spočítej zpaměti: 67 + 48', s: ['67 + 48 = 67 + 40 + 8 = 107 + 8 = <b>115</b>'] },
  { q: 'Spočítej zpaměti: 125 × 8', s: ['125 × 8 = 125 × 4 × 2 = 500 × 2 = <b>1 000</b>'] },
  { q: 'Odhadni výsledek: 198 × 5. Pak spočítej přesně.', s: ['Odhad: 200 × 5 = 1 000', 'Přesně: (200 − 2) × 5 = 1 000 − 10 = <b>990</b>'] },
 ],
 video: null,
},

'1-2': {
 mistakes: [
  {wrong:'2,3 × 1,4 = 32,2', right:'23 × 14 = 322 → 2 des. místa → 3,22', why:'Počet desetinných míst výsledku je součet des. míst činitelů (1+1 = 2), ne opsat čárku z jednoho čísla.'},
  {wrong:'9,6 : 0,4 = 2,4 (musí být menší)', right:'96 : 4 = 24', why:'Dělením číslem menším než 1 výsledek ROSTE. Odstraň čárku: 9,6 : 0,4 = 96 : 4 = 24.'},
  {wrong:'3,7 + 2,45 = 6,82 (zarovnám zprava)', right:'3,70 + 2,45 = 6,15', why:'Zarovnává se čárka pod čárku, ne poslední číslice. Doplň nulu: 3,70.'},
 ],
 intro: '🏺 Hlíněný džbán skrývá záhadu: kolik vody v něm přesně je? Musíš pracovat s desetinnými čísly — a dávat pozor na čárku!',
 sections: [
  { h: 'Co je desetinné číslo?',
    p: ['Desetinné číslo zapisujeme s <b>desetinnou čárkou</b> (v Česku čárka, ne tečka!). Číslo 3,7 = 3 + 7/10.',
        'Místní hodnoty: 12,345 → 1 desítka, 2 jednotky, 3 desetiny, 4 setiny, 5 tisíciny.',
        'Přidáme-li za čárku nuly, hodnota se nemění: 3,7 = 3,70 = 3,700.'] },
  { h: 'Sčítání a odčítání — zarovnej čárky!',
    p: ['<b>Zlaté pravidlo:</b> čárky musí být přesně pod sebou. Pak počítáš jako celá čísla.',
        'Příklad: 3,7 + 2,45 → doplň nulu: 3,<b>70</b> + 2,45 = <b>6,15</b>.',
        'Odčítání: 8,3 − 2,76 → doplň: 8,<b>30</b> − 2,76 = <b>5,54</b>.'] },
  { h: 'Násobení — spočítej desetinná místa',
    p: ['<b>Postup:</b> počítej bez čárek, pak doplň čárku — počet desetinných míst výsledku = součet des. míst obou čísel.',
        'Příklad: 2,3 × 1,4 → 23 × 14 = 322; obě čísla mají dohromady <b>2 des. místa</b> → výsledek <b>3,22</b>.',
        'Násobení mocninami 10: 3,7 × 10 = 37; 3,7 × 100 = 370; 3,7 × 0,01 = 0,037 (čárku posouváme vlevo).'] },
  { h: 'Dělení — zbav se desetinné čárky ve jmenovateli',
    p: ['<b>Trik:</b> vynásob oba členy stejnou mocninou 10, aby byl dělitel celé číslo.',
        '4,5 : 0,3 = 45 : 3 = <b>15</b>. &emsp; 8,4 : 1,2 = 84 : 12 = <b>7</b>.',
        '<span style="color:#ff5555">⚠️ Pozor:</span> 9,6 : 0,4 = 96 : 4 = <b>24</b>. Výsledek je <i>větší</i> než 9,6 — dělíme číslem menším než 1, takže výsledek roste!'] },
 ],
 formulas: [
  '<b>a,bc × 10 = ab,c</b> (posun čárky o 1 vpravo)',
  '<b>a,bc : 10 = 0,abc</b> (posun čárky o 1 vlevo)',
  '<b>a,b × c,d:</b> des. míst výsledku = des. míst(a,b) + des. míst(c,d)',
  '<b>a : 0,b = 10a : b</b> (odstraň čárku násobením 10)',
 ],
 examples: [
  { q: 'Spočítej: 5,08 + 3,7', s: ['Zarovnej: 5,08 + 3,70', 'Výsledek: <b>8,78</b>'] },
  { q: 'Spočítej: 2,4 × 3,5', s: ['24 × 35 = 840', 'Celkem 2 des. místa → <b>8,40</b>'] },
  { q: 'Spočítej: 9,6 : 0,4', s: ['Vynásobíme 10: 96 : 4 = <b>24</b>', 'Výsledek je větší než 9,6 — správně!'] },
 ],
 video: { id: '8-H_UX9zCzM', title: 'Zaokrouhlování desetinných čísel' }
},

'1-3': {
 mistakes: [
  {wrong:'1 m² = 100 cm²', right:'1 m² = 10 000 cm²', why:'Při převodu obsahu se koeficient umocňuje: (100 cm)² = 10 000 cm². Nezapomeň na druhou mocninu.'},
  {wrong:'Obsah trojúhelníku = a · (boční strana) / 2', right:'S = a · v_a / 2, kde v_a je KOLMÁ výška', why:'Do vzorce patří výška kolmá na základnu, ne délka ramene. U tupoúhlého trojúhelníku výška padá i mimo stranu.'},
  {wrong:'Obvod obdélníku 8×5 = 40 cm', right:'o = 2·(8+5) = 26 cm (40 je obsah)', why:'Součin stran dává obsah (cm²), obvod je součet všech stran.'},
 ],
 intro: '🧱 Kamenná dlažba chrámu má záhadné rozměry. Vypočítej obvody a obsahy základních obrazců, abys postoupil dál!',
 sections: [
  { h: 'Obvod rovinného obrazce',
    p: ['Obvod = součet délek všech stran. Jednotka: cm, m, …',
        'Obsah = plocha uvnitř obrazce. Jednotka: cm², m², …'] },
  { h: 'Čtverec a obdélník',
    p: ['<b>Čtverec</b> se stranou <i>a</i>: obvod <b>o = 4a</b>, obsah <b>S = a²</b>.',
        '<b>Obdélník</b> se stranami <i>a</i>, <i>b</i>: obvod <b>o = 2(a + b)</b>, obsah <b>S = a · b</b>.'] },
  { h: 'Trojúhelník — výška musí být kolmá!',
    p: ['<b>Trojúhelník</b> se stranami <i>a</i>, <i>b</i>, <i>c</i>: obvod <b>o = a + b + c</b>.',
        'Obsah: <b>S = (a · v<sub>a</sub>) / 2</b>, kde v<sub>a</sub> je <i>výška na stranu a</i>.',
        '<span style="color:#ff5555">⚠️ Výška v<sub>a</sub> musí být KOLMÁ k základně a!</span> Není to délka boční strany — u tupoúhlého trojúhelníku výška padá mimo stranu.',
        '<svg width="260" height="120" style="display:block;margin:8px auto 0" viewBox="0 0 260 120"><polygon points="30,100 200,100 90,20" fill="none" stroke="#4a9eff" stroke-width="2"/><line x1="90" y1="20" x2="90" y2="100" stroke="#ffcc00" stroke-width="2" stroke-dasharray="6,4"/><rect x="85" y="95" width="10" height="10" fill="none" stroke="#ffcc00" stroke-width="1.5"/><text x="115" y="115" fill="#c9d1d9" font-size="14" font-family="sans-serif">a</text><text x="93" y="60" fill="#ffcc00" font-size="13" font-family="sans-serif">v_a</text><text x="24" y="113" fill="#4a9eff" font-size="13" font-family="sans-serif">A</text><text x="202" y="113" fill="#4a9eff" font-size="13" font-family="sans-serif">B</text><text x="83" y="15" fill="#4a9eff" font-size="13" font-family="sans-serif">C</text></svg>'] },
  { h: 'Přepočet jednotek obsahu',
    p: ['<b>Pozor:</b> při přepočtu obsahu musíš umocnit koeficient!',
        '1 m² = (100 cm)² = <b>10 000 cm²</b>. Ne 100 cm² !',
        '1 km² = (1 000 m)² = 1 000 000 m² = 100 ha.'] },
 ],
 formulas: [
  '<b>Čtverec:</b> o = 4a, &ensp; S = a²',
  '<b>Obdélník:</b> o = 2(a + b), &ensp; S = a · b',
  '<b>Trojúhelník:</b> o = a + b + c, &ensp; S = (a · v<sub>a</sub>) / 2',
 ],
 examples: [
  { q: 'Obdélník má strany 8 cm a 5 cm. Obvod a obsah?', s: ['o = 2 × (8 + 5) = 2 × 13 = <b>26 cm</b>', 'S = 8 × 5 = <b>40 cm²</b>'] },
  { q: 'Trojúhelník má základnu 12 cm a výšku na ni 7 cm. Obsah?', s: ['S = (12 × 7) / 2 = 84 / 2 = <b>42 cm²</b>'] },
  { q: 'Převeď: 2,5 m² = ? cm²', s: ['1 m² = 10 000 cm²', '2,5 × 10 000 = <b>25 000 cm²</b>'] },
 ],
 video: { id: 'GcR_xKAu5kQ', title: 'Obvod a obsah čtverce a obdélníku' },
},

/* ─── Oblast 2: SÍŇ ZLOMKŮ ───────────────────────────────────── */

'2-1': {
 mistakes: [
  {wrong:'Zkrácení 24/36: 24−12 / 36−12 = 12/24', right:'24:12 / 36:12 = 2/3', why:'Krátí se dělením čitatele i jmenovatele stejným číslem, ne odčítáním.'},
  {wrong:'Rozšíření 3/4 na dvacetiny: 15/4', right:'3·5 / 4·5 = 15/20', why:'Rozšiřuje se čitatel I jmenovatel stejným číslem. Když se změní jen čitatel, změní se hodnota zlomku.'},
  {wrong:'6/10 zkrátím jen čitatele na 3/10', right:'6/10 = 3/5 (děl obě čísla dvěma)', why:'Krácení platí pro čitatele i jmenovatele současně, jinak už zlomek neoznačuje stejnou část.'},
 ],
 intro: '📜 Písař zlomků střeží posvátný svitek. Aby sis ho zasloužil, musíš zlomky zkracovat a rozšiřovat jako pravý matematik!',
 sections: [
  { h: 'Co je zlomek?',
    p: ['Zlomek <b>a/b</b> říká: rozděl celek na <i>b</i> stejných dílů a vezmi <i>a</i> z nich. Číslo <i>a</i> = čitatel, <i>b</i> = jmenovatel (b ≠ 0).',
        'Typy: <b>vlastní</b> (a &lt; b, hodnota &lt; 1), <b>nevlastní</b> (a ≥ b, hodnota ≥ 1), <b>smíšené číslo</b> (celá část + vlastní zlomek, např. 2&frac34;).',
        '<svg width="280" height="60" style="display:block;margin:8px auto 0" viewBox="0 0 280 60"><text x="4" y="14" fill="#ffcc00" font-size="12" font-family="sans-serif">6/8:</text><rect x="30" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="47" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="64" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="81" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="98" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="115" y="2" width="16" height="28" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="132" y="2" width="16" height="28" rx="2" fill="none" stroke="#4a9eff" stroke-width="1.5"/><rect x="149" y="2" width="16" height="28" rx="2" fill="none" stroke="#4a9eff" stroke-width="1.5"/><text x="4" y="54" fill="#ffcc00" font-size="12" font-family="sans-serif">3/4:</text><rect x="30" y="32" width="33" height="26" rx="2" fill="#00ff88" opacity="0.8"/><rect x="64" y="32" width="33" height="26" rx="2" fill="#00ff88" opacity="0.8"/><rect x="98" y="32" width="33" height="26" rx="2" fill="#00ff88" opacity="0.8"/><rect x="132" y="32" width="33" height="26" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/><text x="175" y="22" fill="#c9d1d9" font-size="20" font-family="sans-serif">=</text></svg>'] },
  { h: 'Zkracování zlomků',
    p: ['Zlomek krátíme tak, že čitatele i jmenovatele vydělíme stejným číslem &gt; 1. Hodnota zlomku se nemění.',
        '<b>Nejlepší postup:</b> dělíme největším společným dělitelem (NSD) — hned dostaneme základní tvar.',
        'NSD(12, 18) = 6 → 12/18 = (12:6)/(18:6) = <b>2/3</b>. Základní tvar: NSD(čitatel, jmenovatel) = 1.'] },
  { h: 'Rozšiřování zlomků',
    p: ['Čitatele i jmenovatele <i>vynásobíme</i> stejným číslem ≠ 0. Hodnota zlomku se nemění.',
        '2/5 = (2×3)/(5×3) = <b>6/15</b>. Rozšiřujeme hlavně proto, abychom sladili jmenovatele před sčítáním.'] },
  { h: 'Jak najít NSD',
    p: ['<b>Rozklad na prvočinitele:</b> 12 = 2² × 3, 18 = 2 × 3². NSD = 2¹ × 3¹ = <b>6</b>.',
        '<b>Eukleidův algoritmus</b> (rychlejší pro velká čísla): NSD(18, 12): 18 = 1×12 + 6; 12 = 2×6 + 0 → NSD = <b>6</b>.'] },
 ],
 formulas: [
  '<b>Krácení:</b> a/b = (a:k)/(b:k), kde k dělí oba; nejlépe k = NSD(a,b)',
  '<b>Rozšiřování:</b> a/b = (a×k)/(b×k) pro libovolné k ≠ 0',
  '<b>Základní tvar:</b> NSD(čitatel, jmenovatel) = 1',
 ],
 examples: [
  { q: 'Zkrať 24/36 na základní tvar', s: ['NSD(24, 36) = 12', '24/36 = (24:12)/(36:12) = <b>2/3</b>'] },
  { q: 'Rozšiř 3/4 na jmenovatel 20', s: ['4 × 5 = 20 → rozšiřujeme 5×', '3/4 = (3×5)/(4×5) = <b>15/20</b>'] },
  { q: 'Jsou zlomky 6/10 a 9/15 stejné?', s: ['6/10 = 3/5 (krátíme 2×)', '9/15 = 3/5 (krátíme 3×)', 'Oba mají základní tvar 3/5 → <b>ANO, jsou si rovny</b>'] },
 ],
 video: { id: 'A05HhHZwfoQ', title: 'Krácení zlomků' },
},

'2-2': {
 mistakes: [
  {wrong:'1/2 + 1/3 = 2/5', right:'3/6 + 2/6 = 5/6', why:'Jmenovatele se NESČÍTAJÍ. Nejdřív sjednoť jmenovatele (NSN = 6), teprve pak sečti čitatele.'},
  {wrong:'3/4 + 2/6 = 5/10', right:'9/12 + 4/12 = 13/12', why:'Nelze sčítat čitatele i jmenovatele napříč. Převeď na společný jmenovatel (NSN 12).'},
  {wrong:'2 1/3 = 2 · 1/3 = 2/3', right:'2 1/3 = (2·3 + 1)/3 = 7/3', why:'Smíšené číslo je celek PLUS zlomek. Na nevlastní zlomek: celek × jmenovatel + čitatel.'},
 ],
 intro: '🪶 Duch papyru se probouzí! Chce vidět, jak sčítáš a odčítáš zlomky s různými jmenovateli. Nezklam ho!',
 sections: [
  { h: 'Stejné jmenovatele — snadné',
    p: ['Je-li jmenovatel stejný, stačí sečíst (odečíst) čitatele. Jmenovatel zůstává.',
        '3/7 + 2/7 = <b>5/7</b>. &ensp; 5/6 − 1/6 = <b>4/6 = 2/3</b> (zkrátíme!).'] },
  { h: 'Různé jmenovatele — najdi NSN',
    p: ['Nejprve najdi <b>nejmenší společný násobek (NSN)</b> jmenovatelů — to je nový společný jmenovatel.',
        'NSN(4, 6): 4 = 2², 6 = 2×3 → NSN = 2² × 3 = <b>12</b>.',
        'Rozšíříme oba zlomky: 1/4 = 3/12, &ensp; 1/6 = 2/12. Pak: 3/12 + 2/12 = <b>5/12</b>.',
        '<svg width="280" height="54" style="display:block;margin:8px auto 0" viewBox="0 0 280 54"><text x="4" y="14" fill="#4a9eff" font-size="12" font-family="sans-serif">1/4</text><rect x="30" y="2" width="55" height="20" rx="2" fill="#4a9eff" opacity="0.8"/><rect x="86" y="2" width="55" height="20" rx="2" fill="none" stroke="#4a9eff" stroke-width="1.5"/><rect x="142" y="2" width="55" height="20" rx="2" fill="none" stroke="#4a9eff" stroke-width="1.5"/><rect x="198" y="2" width="55" height="20" rx="2" fill="none" stroke="#4a9eff" stroke-width="1.5"/><text x="4" y="48" fill="#00ff88" font-size="12" font-family="sans-serif">1/6</text><rect x="30" y="28" width="37" height="20" rx="2" fill="#00ff88" opacity="0.8"/><rect x="68" y="28" width="37" height="20" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/><rect x="106" y="28" width="37" height="20" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/><rect x="144" y="28" width="37" height="20" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/><rect x="182" y="28" width="37" height="20" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/><rect x="220" y="28" width="37" height="20" rx="2" fill="none" stroke="#00ff88" stroke-width="1.5"/></svg>'] },
  { h: 'Postup krok za krokem',
    p: ['1. Najdi NSN jmenovatelů.',
        '2. Rozšiř každý zlomek na tento jmenovatel.',
        '3. Sečti (odečti) čitatele — jmenovatel se nemění.',
        '4. Zkrať výsledek na základní tvar.'] },
  { h: 'Smíšená čísla',
    p: ['Smíšené číslo → nevlastní zlomek: 2&frac34; = (2×4 + 3)/4 = <b>11/4</b>. Pak počítej běžně.',
        'Výsledek zpět: 17/5 = 3 zbytek 2 → 3&nbsp;2/5.'] },
 ],
 formulas: [
  '<b>Stejný jmenovatel:</b> a/n ± b/n = (a ± b)/n',
  '<b>Různé jmenovatele:</b> rozšiř na NSN(b,d), pak sečti čitatele',
  '<b>Smíšené číslo → zlomek:</b> k&nbsp;a/b = (k·b + a)/b',
 ],
 examples: [
  { q: 'Spočítej: 3/4 + 2/6', s: ['NSN(4, 6) = 12', '3/4 = 9/12, &ensp; 2/6 = 4/12', '9/12 + 4/12 = 13/12 = <b>1&nbsp;1/12</b>'] },
  { q: 'Spočítej: 2&nbsp;1/3 − 5/6', s: ['2&nbsp;1/3 = 7/3', 'NSN(3, 6) = 6 → 7/3 = 14/6', '14/6 − 5/6 = 9/6 = 3/2 = <b>1&nbsp;1/2</b>'] },
  { q: 'Snědl jsi 1/3 a 1/4 dortu. Kolik zbývá?', s: ['Snědeno: 1/3 + 1/4 = 4/12 + 3/12 = 7/12', 'Zbývá: 1 − 7/12 = <b>5/12 dortu</b>'] },
 ],
 video: { id: 'fhe7WsRPDa0', title: 'Sčítání a odčítání zlomků' },
},

'2-3': {
 mistakes: [
  {wrong:'3/5 : 2/7 = 6/35', right:'3/5 × 7/2 = 21/10', why:'Dělení zlomkem = násobení PŘEVRÁCENÝM zlomkem. Nesmí se rovnou násobit původní zlomky.'},
  {wrong:'4 : 1/2 = 2', right:'4 × 2/1 = 8', why:'Dělení číslem menším než 1 dává větší výsledek. „Kolik půlek je ve 4?" → 8.'},
  {wrong:'Násobení 3/5 × 2/7 prý nejde bez společného jmenovatele', right:'čitatel×čitatel, jmenovatel×jmenovatel = 6/35', why:'Společný jmenovatel je potřeba jen u sčítání a odčítání, u násobení ne.'},
 ],
 intro: '🐍 Had hieroglyfů se plazí chodbou — zlomky musíš násobit a dělit. Jedovatý zub má, ale pravidla tě ochrání!',
 sections: [
  { h: 'Násobení zlomků',
    p: ['Čitatel × čitatel, jmenovatel × jmenovatel. <b>Společný jmenovatel nepotřebuješ!</b>',
        '3/5 × 2/7 = (3×2)/(5×7) = <b>6/35</b>.',
        '<b>Tip — krácení křížem před násobením:</b> 3/10 × 5/6 → zkrátíme 5:5 a 10:5, pak 3:3 a 6:3 → 1/2 × 1/2 = <b>1/4</b>. Čísla zůstanou malá.',
        '<b>Slovní spojení:</b> „polovina ze tří čtvrtin" = 1/2 × 3/4 = 3/8.'] },
  { h: 'Převrácené číslo (reciproká hodnota)',
    p: ['Převrácené číslo k a/b je b/a. Platí: a/b × b/a = 1.',
        'Příklady: k 3/4 je 4/3; k 5 (= 5/1) je 1/5; k 2/3 je 3/2.'] },
  { h: 'Dělení zlomků',
    p: ['Dělení zlomkem = násobení převráceným zlomkem.',
        '<b>a/b : c/d = a/b × d/c</b>.',
        'Příklad: 3/5 : 2/7 = 3/5 × 7/2 = 21/10 = <b>2&nbsp;1/10</b>.',
        '<span style="color:#ff5555">⚠️ Dělíme-li zlomkem menším než 1, výsledek je VĚTŠÍ než původní číslo!</span> Např. 4 : 1/2 = 4 × 2 = 8.'] },
 ],
 formulas: [
  '<b>Násobení:</b> a/b × c/d = (a·c)/(b·d)',
  '<b>Dělení:</b> a/b : c/d = a/b × d/c = (a·d)/(b·c)',
  '<b>Zlomek z čísla:</b> a/b z n = n × a/b',
 ],
 examples: [
  { q: 'Spočítej: 4/9 × 3/8', s: ['Krácení křížem: 4 a 8 → :4: 1 a 2; 3 a 9 → :3: 1 a 3', '1/3 × 1/2 = <b>1/6</b>'] },
  { q: 'Spočítej: 5/6 : 10/3', s: ['5/6 × 3/10 = 15/60 = <b>1/4</b>'] },
  { q: 'Kolik je polovina ze tří čtvrtin?', s: ['1/2 × 3/4 = 3/8'] },
 ],
 video: { id: 'zmNQViemnXk', title: 'Násobení a dělení zlomků' },
},

/* ─── Oblast 3: PODZEMNÍ MRAZÍRNA ─────────────────────────────── */

'3-1': {
 mistakes: [
  {wrong:'−3 − 5 = −2', right:'−3 − 5 = −8', why:'Obě čísla táhnou na ose doleva (−3 a ještě o 5 níž). Znaménka jsou stejná, vzdálenosti se sčítají: −8.'},
  {wrong:'5 − (−3) = 2', right:'5 − (−3) = 5 + 3 = 8', why:'Odečíst záporné = přičíst kladné. Dvě minus za sebou dají plus.'},
  {wrong:'(−7) + (+3) = −10', right:'−4', why:'Různá znaménka: od většího |7| odečti menší |3| = 4, znaménko převezme větší (−). Sčítá se jen při stejných znaménkách.'},
 ],
 intro: '❄️ Ledový strážce chrámových sklepů křičí: „Záporná čísla tě zmrazí, pokud je neovládáš!" Nauč se pohybovat na číselné ose!',
 sections: [
  { h: 'Celá čísla a číselná osa',
    p: ['Celá čísla ℤ = {…, −3, −2, −1, 0, 1, 2, 3, …}. Záporná jsou <b>vlevo od nuly</b>, kladná vpravo.',
        'Čím více vlevo, tím menší: −5 &lt; −2 &lt; 0 &lt; 3. Opačné číslo k <i>a</i> je −<i>a</i>.',
        '<svg width="280" height="40" style="display:block;margin:8px auto 0" viewBox="0 0 280 40"><line x1="10" y1="20" x2="270" y2="20" stroke="#4a9eff" stroke-width="2"/><polygon points="270,15 280,20 270,25" fill="#4a9eff"/><line x1="10" y1="15" x2="10" y2="25" stroke="#4a9eff" stroke-width="2"/><text x="7" y="38" fill="#c9d1d9" font-size="11" font-family="sans-serif">−5</text><line x1="54" y1="16" x2="54" y2="24" stroke="#4a9eff" stroke-width="1.5"/><text x="51" y="38" fill="#c9d1d9" font-size="11" font-family="sans-serif">−4</text><line x1="98" y1="16" x2="98" y2="24" stroke="#4a9eff" stroke-width="1.5"/><text x="95" y="38" fill="#c9d1d9" font-size="11" font-family="sans-serif">−3</text><line x1="142" y1="16" x2="142" y2="24" stroke="#4a9eff" stroke-width="1.5"/><text x="139" y="38" fill="#c9d1d9" font-size="11" font-family="sans-serif">−2</text><line x1="186" y1="16" x2="186" y2="24" stroke="#4a9eff" stroke-width="1.5"/><text x="183" y="38" fill="#c9d1d9" font-size="11" font-family="sans-serif">−1</text><circle cx="230" cy="20" r="5" fill="#ffcc00"/><text x="227" y="38" fill="#ffcc00" font-size="11" font-family="sans-serif">0</text><line x1="10" y1="16" x2="10" y2="24" stroke="#4a9eff" stroke-width="1.5"/></svg>'] },
  { h: 'Sčítání celých čísel',
    p: ['<b>(+) + (+):</b> normálně. &ensp; (+3) + (+5) = +8.',
        '<b>(−) + (−):</b> sečti absolutní hodnoty, přidej −. &ensp; (−3) + (−5) = −8.',
        '<b>Různá znaménka:</b> od většího (|…|) odečti menší, znaménko přebere větší. &ensp; (+7) + (−3) = +4; &ensp; (+3) + (−7) = −4.'] },
  { h: 'Odčítání celých čísel — klíčové pravidlo',
    p: ['<b>Odečíst číslo = přičíst číslo opačné:</b> a − b = a + (−b).',
        '5 − (−3) = 5 + 3 = <b>8</b>. &ensp; Dvě minusová znaménka za sebou → <b>plus</b>.',
        '−4 − (−6) = −4 + 6 = <b>2</b>.',
        'Pravidlo: „− (−) = +" a „− (+) = −".'] },
 ],
 formulas: [
  '<b>a − (−b) = a + b</b>',
  '<b>(−a) + (−b) = −(a + b)</b>',
  '<b>|a|</b> = absolutní hodnota (vzdálenost od nuly, vždy ≥ 0)',
 ],
 examples: [
  { q: 'Spočítej: (−8) + (+5)', s: ['|−8| &gt; |+5|, znaménko: minus', '(−8) + (+5) = <b>−3</b>'] },
  { q: 'Spočítej: 3 − (−7)', s: ['3 − (−7) = 3 + 7 = <b>10</b>'] },
  { q: 'Spočítej: (−4) − (−9)', s: ['(−4) − (−9) = −4 + 9 = <b>5</b>'] },
 ],
 video: { id: 'd_w3jiDwUbk', title: 'Sčítání a odčítání záporných čísel' },
},

'3-2': {
 mistakes: [
  {wrong:'−3² = 9', right:'−3² = −(3²) = −9; jen (−3)² = 9', why:'Bez závorky umocňuješ jen trojku a minus zůstane před ní. Se závorkou (−3)² se umocňuje i znaménko.'},
  {wrong:'(−2) × (−5) = −10', right:'+10', why:'Záporné krát záporné je kladné. Sudý počet minusů → kladný výsledek.'},
  {wrong:'(−2)³ = 8', right:'(−2)³ = −8', why:'Lichá mocnina záporného čísla je záporná (− · − · − = −).'},
 ],
 intro: '🧊 Krystalový golem tě zasype ledem! Pravidla znamének při násobení a dělení ti ho porazí. Pozor na závorky!',
 sections: [
  { h: 'Pravidla znamének — tabulka',
    p: ['<table style="border-collapse:collapse;margin:4px 0"><tr><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ffcc00">(+) × (+)</td><td style="padding:3px 10px;border:1px solid #4a9eff;color:#00ff88">= (+)</td></tr><tr><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ffcc00">(−) × (−)</td><td style="padding:3px 10px;border:1px solid #4a9eff;color:#00ff88">= (+)</td></tr><tr><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ffcc00">(+) × (−)</td><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ff5555">= (−)</td></tr><tr><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ffcc00">(−) × (+)</td><td style="padding:3px 10px;border:1px solid #4a9eff;color:#ff5555">= (−)</td></tr></table>',
        '<b>Rychlé pravidlo:</b> lichý počet záporných čísel → záporný výsledek; sudý počet → kladný.'] },
  { h: 'Dělení — stejná pravidla',
    p: ['Znaménka fungují identicky jako u násobení.',
        '(−12) : (−3) = <b>+4</b> &ensp; (obě záporná → kladný).',
        '(−12) : (+3) = <b>−4</b> &ensp; (různá znaménka → záporný).'] },
  { h: 'Mocniny záporných čísel',
    p: ['(−2)² = (−2) × (−2) = <b>+4</b> (sudá mocnina → vždy kladná).',
        '(−2)³ = (−2)×(−2)×(−2) = −8 (lichá mocnina → záporná).',
        '<span style="color:#ff5555">⚠️ Závorka mění vše: (−3)² = 9, ale −3² = −(3²) = −9!</span>'] },
 ],
 formulas: [
  '<b>(+) × (+) = (+)</b>',
  '<b>(−) × (−) = (+)</b>',
  '<b>(+) × (−) = (−)</b>',
  '<b>(−a)<sup>n</sup> = +a<sup>n</sup></b> pro sudé n, &ensp; <b>= −a<sup>n</sup></b> pro liché n',
 ],
 examples: [
  { q: 'Spočítej: (−5) × (−8)', s: ['obě záporná → kladný výsledek', '5 × 8 = 40 → <b>+40</b>'] },
  { q: 'Spočítej: (−36) : (+4)', s: ['různá znaménka → záporný výsledek', '36 : 4 = 9 → <b>−9</b>'] },
  { q: 'Spočítej: (−3)⁴', s: ['sudá mocnina záporného čísla → kladná', '3⁴ = 81 → <b>+81</b>'] },
 ],
 video: { id: 'zxS8ylGtYDU', title: 'Násobení a dělení záporných čísel' },
},

'3-3': {
 mistakes: [
  {wrong:'−3/4 > −1/2 (protože 3 > 1)', right:'−3/4 < −1/2', why:'U záporných čísel je to opačně: čím větší číslo za minusem, tím menší hodnota. −6/10 < −5/10.'},
  {wrong:'|−5| = −5', right:'|−5| = 5', why:'Absolutní hodnota je vzdálenost od nuly, vždy nezáporná. Minus se „ztratí".'},
  {wrong:'√2 je racionální', right:'√2 je iracionální (nejde zapsat jako zlomek)', why:'Racionální je jen to, co lze zapsat jako p/q celých čísel. √2 = 1,4142… bez periody, nelze.'},
 ],
 intro: '🌀 Vír mrazu tě pohlcuje! Zachrání tě racionální čísla — ta, která jdou zapsat jako zlomek. Všechno ostatní je iracionální!',
 sections: [
  { h: 'Co jsou racionální čísla ℚ?',
    p: ['<b>Racionální číslo</b> = číslo, které lze zapsat ve tvaru p/q, kde p ∈ ℤ a q ∈ ℤ, q ≠ 0.',
        'Do ℚ patří: celá čísla (5 = 5/1), zlomky (3/4), záporné zlomky (−2/5), desetinná čísla s konečným zápisem (0,3 = 3/10), <b>periodická</b> desetinná čísla (0,333… = 1/3).',
        'Do ℚ <b>nepatří</b> např. √2 nebo π — ta nelze zapsat jako zlomek celých čísel.'] },
  { h: 'Racionální čísla na číselné ose',
    p: ['Každé racionální číslo má přesné místo na číselné ose. Záporné zlomky jsou vlevo od nuly.',
        '<b>Porovnávání:</b> převeď na společný jmenovatel. −1/2 = −2/4, −3/4 = −3/4. Protože −2 &gt; −3, platí <b>−1/2 &gt; −3/4</b>.'] },
  { h: 'Absolutní hodnota',
    p: ['<b>|a|</b> = vzdálenost čísla <i>a</i> od nuly na číselné ose. Vždy ≥ 0.',
        '|−5| = 5, &ensp; |3| = 3, &ensp; |0| = 0, &ensp; |−2/3| = 2/3.',
        'Formálně: |a| = a pro a ≥ 0; &ensp; |a| = −a pro a &lt; 0 (výsledek je kladný!).'] },
  { h: 'Operace s racionálními čísly',
    p: ['Kombinuješ pravidla pro zlomky + pravidla pro znaménka.',
        '(−3/4) + (1/2) = (−3/4) + (2/4) = <b>−1/4</b>.',
        '(−2/3) × (−3/5) = +(2×3)/(3×5) = 6/15 = <b>2/5</b>.'] },
 ],
 formulas: [
  '<b>ℚ = { p/q | p ∈ ℤ, q ∈ ℤ, q ≠ 0 }</b>',
  '<b>|a| ≥ 0</b> pro každé a',
  '<b>|a × b| = |a| × |b|</b>',
 ],
 examples: [
  { q: 'Porovnej: −3/5 a −1/2', s: ['NSN(5, 2) = 10', '−3/5 = −6/10, &ensp; −1/2 = −5/10', 'Protože −6 &lt; −5, platí <b>−3/5 &lt; −1/2</b>'] },
  { q: 'Spočítej: (−2/3) × (−9/4)', s: ['(−) × (−) = (+)', '(2×9)/(3×4) = 18/12 = <b>3/2 = 1,5</b>'] },
  { q: 'Je číslo √9 racionální?', s: ['√9 = 3, a 3 = 3/1', 'Lze zapsat jako zlomek → <b>ANO, je racionální</b>'] },
 ],
 video: { id: 'ME5pLObMogw', title: 'Racionální čísla — zlomky' }
},

/* ─── Oblast 4: VÁŽNICE POMĚRŮ ────────────────────────────────── */

'4-1': {
 mistakes: [
  {wrong:'240 Kč v poměru 1:2:3 → 240:1, 240:2, 240:3', right:'6 dílů, 1 díl = 240 : 6 = 40 → 40, 80, 120', why:'Nejdřív sečti členy poměru (počet dílů), pak hodnotu jednoho dílu, pak násob. Celek se nedělí přímo členy.'},
  {wrong:'Zjednodušení 12:18 = 12−6 : 18−6 = 6:12', right:'12:6 : 18:6 = 2:3', why:'Poměr se zjednodušuje dělením všech členů NSD, ne odčítáním.'},
  {wrong:'Poměr 3:5 zapíšu klidně jako 5:3', right:'pořadí musí odpovídat zadání', why:'3:5 a 5:3 jsou různé poměry. Musíš dodržet, které číslo patří které veličině.'},
 ],
 intro: '⚖️ Strážce zlatých vah potřebuje znát poměr. Bez znalosti poměrů z vážnice nevyjdeš — a bez kódu se brána neotevře!',
 sections: [
  { h: 'Co je poměr?',
    p: ['Poměr <b>a : b</b> (čti „a ku b") vyjadřuje vzájemnou relaci dvou čísel. Na každé <i>a</i> dílů jednoho připadá <i>b</i> dílů druhého.',
        'Poměr 3 : 5 → celkem 8 dílů; první dostane 3/8, druhý 5/8.',
        'Úzce souvisí se zlomkem: 3 : 5 odpovídá zlomku 3/5 (ale není to totéž!).'] },
  { h: 'Zjednodušování poměru',
    p: ['Dělíme oba (všechny) členy NSD — stejně jako krácení zlomku.',
        '12 : 18 = (12:6) : (18:6) = <b>2 : 3</b>.',
        'Tři členy: 6 : 9 : 15 → NSD = 3 → <b>2 : 3 : 5</b>.'] },
  { h: 'Dělení celku v poměru',
    p: ['<b>Postup:</b> spočítej celkový počet dílů (= součet členů poměru), urči hodnotu 1 dílu, pak vypočítej každou část.',
        'Příklad: 240 Kč v poměru 1 : 2 : 3. Celkem 6 dílů. 1 díl = 240 : 6 = 40 Kč.',
        'Části: <b>40 Kč, 80 Kč, 120 Kč</b>. Kontrola: 40+80+120 = 240 ✓'] },
  { h: 'Poměr v praxi',
    p: ['Recept na 4 porce: 300 g mouky. Na 6 porcí? Poměr porcí 4 : 6 = 2 : 3. Mouka: 300 × 3/2 = <b>450 g</b>.',
        'Mapa 1 : 50 000 → 1 cm na mapě = 500 m ve skutečnosti.'] },
 ],
 formulas: [
  '<b>a : b = (a:k) : (b:k)</b>, k = NSD(a, b)',
  '<b>1 díl</b> při dělení C v poměru a:b = C / (a + b)',
  '<b>Části:</b> a/(a+b) × C &ensp; a &ensp; b/(a+b) × C',
 ],
 examples: [
  { q: 'Zjednoduš poměr 36 : 48', s: ['NSD(36, 48) = 12', '36 : 48 = <b>3 : 4</b>'] },
  { q: 'Rozděl 180 cm v poměru 2 : 3 : 4', s: ['Celkem: 2+3+4 = 9 dílů', '1 díl = 180 : 9 = 20 cm', 'Části: <b>40 cm, 60 cm, 80 cm</b>', 'Kontrola: 40+60+80 = 180 ✓'] },
  { q: 'Beton se míchá v poměru cement : písek = 1 : 4. Kolik kg písku na 60 kg směsi?', s: ['Celkem 1+4 = 5 dílů, 1 díl = 60 : 5 = 12 kg', 'Písek = 4 díly = 4 · 12 = <b>48 kg</b>'] },
 ],
 video: { id: 'YeptEbvYohc', title: 'Poměr – slovní úlohy' },
},

'4-2': {
 mistakes: [
  {wrong:'Víc dělníků → víc dní (počítám jako přímou)', right:'víc dělníků → MÉNĚ dní (nepřímá úměrnost)', why:'Vždy si rozmysli směr: „čím víc, tím víc" = přímá, „čím víc, tím míň" = nepřímá.'},
  {wrong:'4 sešity 52 Kč, 1 sešit = 52 × 4', right:'1 sešit = 52 : 4 = 13 Kč', why:'Na jeden kus se dělí (méně kusů → nižší cena), ne násobí.'},
  {wrong:'3 kg = 90 Kč, tak 5 kg = 90 + 2 = 92 Kč', right:'1 kg = 30 Kč, 5 kg = 150 Kč', why:'Úměra není přičítání kilogramů ke koruně. Spočítej cenu za jednotku a přenásob.'},
 ],
 intro: '🐪 Pán karavany potřebuje vědět, za jak dlouho dorazí do oázy. Trojčlenka a přímá úměrnost ho dovedou k cíli!',
 sections: [
  { h: 'Přímá úměrnost',
    p: ['Dvě veličiny jsou <b>přímo úměrné</b>, pokud se jejich poměr nemění: y/x = k (konstanta úměrnosti).',
        'Jak roste x, roste i y (stejným koeficientem). Graf: přímka procházející počátkem.',
        'Příklad: cena za 3 kg = 90 Kč → za 1 kg = 30 Kč → za 5 kg = 150 Kč. Konstanta k = 30 Kč/kg.'] },
  { h: 'Trojčlenka — přímá',
    p: ['Postup: <b>najdi hodnotu pro 1 jednotku, pak přepočítej</b>.',
        '<svg width="260" height="50" style="display:block;margin:8px auto 0" viewBox="0 0 260 50"><rect x="0" y="0" width="260" height="50" rx="4" fill="#161b22" stroke="#4a9eff" stroke-width="1.5"/><text x="10" y="18" fill="#ffcc00" font-size="12" font-family="monospace">položky</text><text x="90" y="18" fill="#c9d1d9" font-size="12" font-family="monospace">3</text><text x="130" y="18" fill="#c9d1d9" font-size="12" font-family="monospace">→</text><text x="150" y="18" fill="#c9d1d9" font-size="12" font-family="monospace">5</text><text x="10" y="38" fill="#ffcc00" font-size="12" font-family="monospace">cena (Kč)</text><text x="90" y="38" fill="#00ff88" font-size="12" font-family="monospace">45</text><text x="130" y="38" fill="#c9d1d9" font-size="12" font-family="monospace">→</text><text x="150" y="38" fill="#4a9eff" font-size="12" font-family="monospace">?</text></svg>',
        '1 položka = 45 : 3 = 15 Kč. &ensp; 5 položek = 15 × 5 = <b>75 Kč</b>.'] },
  { h: 'Jak poznat přímou vs. nepřímou úměrnost',
    p: ['<b>Přímá:</b> víc kusů → vyšší cena. „Čím víc, tím víc."',
        '<b>Nepřímá:</b> víc pracovníků → kratší čas. „Čím víc, tím méně."',
        '<span style="color:#ff5555">⚠️ Před každou trojčlenkou si ověř: je to přímá nebo nepřímá úměrnost?</span>'] },
 ],
 formulas: [
  '<b>Přímá úměrnost:</b> y = k·x, &ensp; y₁/x₁ = y₂/x₂',
  '<b>Trojčlenka (přímá):</b> x → y₁; 1 → y₁/x; n → n · (y₁/x)',
 ],
 examples: [
  { q: 'Za 3 hodiny ujede vlak 210 km. Kolik ujede za 5 hodin?', s: ['1 hod → 210 : 3 = 70 km', '5 hod → 70 × 5 = <b>350 km</b>'] },
  { q: '4 sešity stojí 52 Kč. Kolik stojí 7 sešitů?', s: ['1 sešit → 52 : 4 = 13 Kč', '7 sešitů → 13 × 7 = <b>91 Kč</b>'] },
  { q: 'Na 5 dní vystačí 15 kg krmení. Na kolik dní vystačí 24 kg (stejná spotřeba)?', s: ['1 den → 15 : 5 = 3 kg', '24 : 3 = <b>8 dní</b>'] },
 ],
 video: { id: 'Rm7OylsDDts', title: 'Trojčlenka — přímá a nepřímá úměrnost' }
},

'4-3': {
 mistakes: [
  {wrong:'4 dělníci za 12 dní → 6 dělníků: 6/4 × 12 = 18 dní', right:'48 dní práce : 6 = 8 dní', why:'Nepřímá úměrnost: víc dělníků = MÉNĚ dní. Spočítej celkovou práci (4×12) a děl počtem dělníků.'},
  {wrong:'Plocha na mapě 1:1000: 2 cm² → 2 × 1000 = 2000 cm²', right:'2 × 1000² = 2 000 000 cm² = 200 m²', why:'U ploch se měřítko UMOCŇUJE (×M²), u délek jen ×M.'},
  {wrong:'1 : 5 000 je hrubší než 1 : 100 000', right:'1 : 5 000 je podrobnější', why:'Menší jmenovatel = podrobnější mapa. 1:5 000 ukáže víc detailu než 1:100 000.'},
 ],
 intro: '🗺️ Kartograf chrámu potřebuje tvou pomoc. Nepřímá úměrnost a měřítko mapy — bez nich se ztratíš v poušti!',
 sections: [
  { h: 'Nepřímá úměrnost',
    p: ['Dvě veličiny jsou <b>nepřímo úměrné</b>, pokud jejich součin je konstantní: x · y = k.',
        'Jak roste x, klesá y. Graf: hyperbola (ne přímka!).',
        'Příklady: rychlost a čas (více rychlosti → méně času); počet dělníků a dny práce.'] },
  { h: 'Trojčlenka — nepřímá',
    p: ['Postup: <b>spočítej celkový objem práce (pro 1 jednotku), pak přepočítej opačně</b>.',
        '4 dělníci dokončí práci za 12 dní. Za kolik dní 6 dělníků?',
        '1 dělník → 4 × 12 = 48 dní. &ensp; 6 dělníků → 48 : 6 = <b>8 dní</b>.'] },
  { h: 'Měřítko mapy',
    p: ['Měřítko <b>1 : m</b> říká: 1 jednotka na mapě = m jednotek ve skutečnosti.',
        '1 : 50 000 → 1 cm = 50 000 cm = <b>500 m</b> ve skutečnosti.',
        '1 : 5 000 je <i>podrobnější</i> (větší měřítko) než 1 : 100 000.'] },
  { h: 'Přepočet vzdáleností a ploch',
    p: ['<b>Délka:</b> d<sub>skut</sub> = d<sub>mapa</sub> × M.',
        '<b>Plocha:</b> S<sub>skut</sub> = S<sub>mapa</sub> × M². <span style="color:#ff5555">Koeficient se umocňuje!</span>',
        'Příklad (1 : 1 000): 3 cm na plánu → 3 × 1 000 = 3 000 cm = <b>30 m</b>; 2 cm² → 2 × 1 000² = 2 000 000 cm² = <b>200 m²</b>.'] },
 ],
 formulas: [
  '<b>Nepřímá úměrnost:</b> x · y = k, &ensp; x₁·y₁ = x₂·y₂',
  '<b>d<sub>skut</sub> = d<sub>mapa</sub> × M</b>  (M = číslo za 1:)',
  '<b>S<sub>skut</sub> = S<sub>mapa</sub> × M²</b>  (pro plochy)',
 ],
 examples: [
  { q: 'Na mapě 1 : 20 000 měříme 6,5 cm. Jak dlouhá je cesta?', s: ['d = 6,5 × 20 000 = 130 000 cm = <b>1,3 km</b>'] },
  { q: '6 dělníků postaví zeď za 4 dny. Za kolik dní to zvládnou 3 dělníci?', s: ['6 × 4 = 24 dní práce celkem', '3 dělníci → 24 : 3 = <b>8 dní</b>'] },
  { q: 'Na plánu 1 : 1 000 má pozemek plochu 5 cm². Jaká je skutečná plocha?', s: ['Plocha: ×M² → 5 × 1 000² = 5 000 000 cm²', '5 000 000 cm² = <b>500 m²</b>'] },
 ],
 video: { id: 'xGATRuT_yGA', title: 'Nepřímá úměrnost' }
},

/* ─── Oblast 5: ZLATÁ POKLADNICE ──────────────────────────────── */

'5-1': {
 mistakes: [
  {wrong:'15 % z 240 = 240 × 15 = 3 600', right:'240 × 0,15 = 36', why:'Procento se nejdřív převede na setiny: 15 % = 0,15. Násobení rovnou patnácti dá 100× víc.'},
  {wrong:'35 % = 3,5', right:'35 % = 0,35', why:'Procento se dělí stem, ne deseti. 35 % = 35/100 = 0,35.'},
  {wrong:'1 % z 400 = 40', right:'1 % z 400 = 4', why:'1 % je setina — děl základ stem, ne deseti. 400 : 100 = 4.'},
 ],
 intro: '🪙 Hlídač zlatých mincí střeží pokladnici. Bez pochopení procentové části tě sem nepustí — a bez kódu se trezor neotevře!',
 sections: [
  { h: 'Co je procento?',
    p: ['Procento (%) je <b>setina celku</b>. 1 % = 1/100 = 0,01.',
        '100 % = celý základ. 50 % = polovina. 25 % = čtvrtina.',
        'Promile (‰): 1 ‰ = 1/1 000 = 0,001. Používá se např. u alkoholu v krvi nebo u úroků.'] },
  { h: 'Výpočet procentové části',
    p: ['<b>Vzorec:</b> z = C × p / 100 = C × (p/100).',
        'Převeď procento na desetinné číslo: 35 % = 0,35; 7 % = 0,07; 125 % = 1,25.',
        'Příklad: 15 % z 240 = 240 × 0,15 = <b>36</b>.'] },
  { h: 'Praktické tipy',
    p: ['Nejdřív spočítej <b>1 %</b> (vydělíš základ 100), pak přenásob.',
        '1 % z 400 = 4. &ensp; 5 % = 5 × 4 = 20. &ensp; 15 % = 15 × 4 = 60.',
        '<b>10 %</b> je vždy snadné — vydělíš 10. &ensp; <b>5 %</b> = polovina z 10 %. &ensp; <b>1 %</b> = desetina z 10 %.'] },
  { h: 'Trojúhelník procent',
    p: ['Tři veličiny: <b>z</b> (část), <b>C</b> (základ), <b>p</b> (počet %).',
        'Zakryj, co hledáš: <b>z = C × p/100</b>; &ensp; <b>C = z × 100/p</b>; &ensp; <b>p = z/C × 100</b>.'] },
 ],
 formulas: [
  '<b>z = C × p / 100</b>  (procentová část)',
  '<b>C = z × 100 / p</b>  (základ)',
  '<b>p = z / C × 100</b>  (počet procent)',
 ],
 examples: [
  { q: 'Kolik je 25 % z 360?', s: ['z = 360 × 25/100 = 360 × 0,25 = <b>90</b>'] },
  { q: 'DPH (21 %) z ceny 1 200 Kč?', s: ['z = 1 200 × 0,21 = <b>252 Kč</b>'] },
  { q: 'Kolik je 8 % z 350 Kč? (přes 1 %)', s: ['1 % z 350 = 3,50 Kč', '8 % = 8 × 3,50 = <b>28 Kč</b>'] },
 ],
 video: { id: 'GFkEBrieSuA', title: 'Výpočet procentové části' },
},

'5-2': {
 mistakes: [
  {wrong:'Cena vzrostla ze 400 na 500, základ je 500', right:'základ je 400 (původní hodnota)', why:'Procentní změna se počítá vždy z PŮVODNÍ hodnoty. p = 100/400 × 100 = 25 %.'},
  {wrong:'28 ze 40 = 28/40 = 0,7 %', right:'28/40 × 100 = 70 %', why:'Podíl je potřeba ještě vynásobit stem, aby vyšla procenta. 0,7 = 70 %.'},
  {wrong:'36 Kč je 12 %, základ = 36 × 12', right:'C = 36 × 100 : 12 = 300 Kč', why:'Ze známé části a procent se základ počítá jako z × 100 : p, ne prostým násobením.'},
 ],
 intro: '⚱️ Strážce urny tě vyzkouší na obrácené úlohy: dokážeš najít základ nebo počet procent?',
 sections: [
  { h: 'Počet procent p',
    p: ['Máme základ C a část z. Kolik procent?',
        '<b>p = z / C × 100</b>.',
        'Příklad: Ze 40 žáků udělalo test 28. Kolik procent? p = 28/40 × 100 = <b>70 %</b>.'] },
  { h: 'Základ C',
    p: ['Víme část z a počet procent p, hledáme základ.',
        '<b>C = z × 100 / p</b>.',
        'Příklad: 36 Kč je 12 % z čeho? C = 36 × 100 / 12 = <b>300 Kč</b>.',
        '<span style="color:#ff5555">⚠️ Základ je PŮVODNÍ hodnota — ne hodnota po změně!</span> Pokud cena vzrostla ze 400 na 500 Kč, základ je 400, ne 500.'] },
  { h: 'Procentové zvýšení a snížení',
    p: ['<b>Zvýšení o p %:</b> nová = C × (1 + p/100). &ensp; Příklad: 500 × 1,10 = <b>550 Kč</b>.',
        '<b>Snížení o p %:</b> nová = C × (1 − p/100). &ensp; Příklad: 500 × 0,80 = <b>400 Kč</b>.'] },
 ],
 formulas: [
  '<b>p = z / C × 100</b>  (počet procent)',
  '<b>C = z × 100 / p</b>  (základ)',
  '<b>Zvýšení o p %:</b> nová = C × (1 + p/100)',
  '<b>Snížení o p %:</b> nová = C × (1 − p/100)',
 ],
 examples: [
  { q: 'Ze 150 žáků dostalo jedničku 45. Kolik procent?', s: ['p = 45/150 × 100 = 0,3 × 100 = <b>30 %</b>'] },
  { q: '48 Kč je 16 % z jaké ceny?', s: ['C = 48 × 100 / 16 = 4 800 / 16 = <b>300 Kč</b>'] },
  { q: 'Cena vzrostla z 200 Kč na 250 Kč. O kolik procent?', s: ['Změna z = 250 − 200 = 50 Kč, základ C = 200 (původní!)', 'p = 50/200 × 100 = <b>25 %</b>'] },
 ],
 video: { id: 'nLaeLsK824g', title: 'Výpočet počtu procent' },
},

'5-3': {
 mistakes: [
  {wrong:'Zdražení o 20 % a pak sleva 20 % → původní cena', right:'1000 × 1,2 × 0,8 = 960 Kč (méně!)', why:'Druhé procento se počítá z JINÉHO (většího) základu, takže se zdražení a sleva nevyruší.'},
  {wrong:'Po slevě 20 % je 320 Kč, původní = 320 : 0,20', right:'C = 320 : 0,80 = 400 Kč', why:'320 Kč odpovídá 80 % ceny (100 − 20). Dělí se 0,80, ne procentem slevy.'},
  {wrong:'Sleva 30 % z 600: 600 − 30 = 570 Kč', right:'600 × 0,70 = 420 Kč', why:'30 % je podíl z ceny (0,30 × 600 = 180 Kč), ne 30 korun. Odečti procentní část, ne číslo 30.'},
 ],
 intro: '👑 Pokladník faraona ti zadá záludné slovní úlohy. Sleva, zdražení, DPH, zpětný výpočet — a brána do pokladnice se otevře!',
 sections: [
  { h: 'Sleva',
    p: ['<b>Cena po slevě p %:</b> C<sub>nová</sub> = C × (1 − p/100).',
        'Příklad: Mikina 600 Kč, sleva 30 %. Nová cena: 600 × 0,70 = <b>420 Kč</b>.',
        'Rovnou počítáš kolik % zbývá (100 % − 30 % = 70 %) — bez mezikroku.'] },
  { h: 'Zdražení a DPH',
    p: ['<b>Zdražení o p %:</b> C<sub>nová</sub> = C × (1 + p/100).',
        '<b>DPH</b> (daň z přidané hodnoty): v ČR základní sazba <b>21 %</b>, snížená <b>12 %</b>.',
        'Cena bez DPH 300 Kč → s DPH (21 %): 300 × 1,21 = <b>363 Kč</b>.'] },
  { h: 'Zpětný výpočet — základ',
    p: ['Po slevě 20 % vyjde 320 Kč. Jaká byla původní cena?',
        '320 Kč = 80 % původní ceny. → C = 320 / 0,80 = <b>400 Kč</b>.',
        '<span style="color:#ff5555">⚠️ Nedělíme procentem (20 %), ale (1 − p/100) = 0,80!</span>',
        'Obecně: <b>C = hodnota_po_slevě / (1 − p/100)</b>.'] },
 ],
 formulas: [
  '<b>Cena po slevě p %:</b> C × (1 − p/100)',
  '<b>Cena s DPH:</b> C<sub>bez</sub> × (1 + sazba/100)',
  '<b>Zpětný výpočet:</b> C = hodnota / (1 − p/100)',
 ],
 examples: [
  { q: 'Kniha 250 Kč, sleva 12 %. Kolik stojí?', s: ['250 × (1 − 0,12) = 250 × 0,88 = <b>220 Kč</b>'] },
  { q: 'Po zdražení o 25 % stojí výrobek 500 Kč. Kolik stál původně?', s: ['500 = C × 1,25', 'C = 500 / 1,25 = <b>400 Kč</b>'] },
  { q: 'Zboží zdraží o 10 %, pak zlevní o 10 %. Cena byla 1 000 Kč. Kolik stojí teď?', s: ['Po zdražení: 1 000 × 1,10 = 1 100 Kč', 'Po slevě: 1 100 × 0,90 = <b>990 Kč</b> (méně než původně!)'] },
 ],
 video: { id: 'XG7dmH-wMJI', title: 'Procenta – procvičování' },
},

/* ─── Oblast 6: ZRCADLOVÁ SVATYNĚ ─────────────────────────────── */

'6-1': {
 mistakes: [
  {wrong:'Přes osu y: (3, 2) → (3, −2)', right:'(−3, 2)', why:'Osa y je svislá, zrcadlí doleva/doprava → mění se x. Znaménko y se mění až přes osu x.'},
  {wrong:'Obraz posunu na druhou stranu osy, jak vyjde', right:'stejná vzdálenost od osy jako vzor, na kolmici', why:'Osová souměrnost zachovává vzdálenost bodu od osy a spojnice bod–obraz je kolmá na osu.'},
  {wrong:'Obdélník má 4 osy souměrnosti', right:'obdélník má jen 2 osy', why:'Úhlopříčky obdélníku nejsou osy (nepřekryjí ho). Osami jsou jen dvě středové přímky.'},
 ],
 intro: '🪞 Strážce zrcadel tě vyzve: „Najdi obraz každého bodu přes osu." Kdo neovládá osovou souměrnost, v té místnosti zabloudí!',
 sections: [
  { h: 'Osová souměrnost — co to je?',
    p: ['Osová souměrnost je zobrazení: každý bod X zobrazíme na bod X\' tak, aby osa <i>o</i> byla <b>osou úsečky XX\'</b> — prochází středem XX\' a je na ni kolmá.',
        'Jinými slovy: zrcadlíme bod přes přímku <i>o</i>. Vzdálenost od osy se zachovává.'] },
  { h: 'Jak sestrojit obraz bodu',
    p: ['1. Z bodu X sestrojíme kolmici k ose o.',
        '2. Kolmice protne osu v bodě S (střed).',
        '3. Bod X\' leží na kolmici na druhé straně ve vzdálenosti |XS| = |SX\'|.'] },
  { h: 'Osová souměrnost v souřadnicové soustavě',
    p: ['Přes osu <b>y</b>: (x, y) → (−x, y). &ensp; Přes osu <b>x</b>: (x, y) → (x, −y).',
        '<svg width="260" height="160" style="display:block;margin:8px auto 0" viewBox="0 0 260 160"><line x1="130" y1="10" x2="130" y2="150" stroke="#4a9eff" stroke-width="2"/><line x1="10" y1="80" x2="250" y2="80" stroke="#4a9eff" stroke-width="2"/><polygon points="130,10 125,22 135,22" fill="#4a9eff"/><polygon points="250,80 238,75 238,85" fill="#4a9eff"/><text x="135" y="20" fill="#4a9eff" font-size="12" font-family="sans-serif">y</text><text x="238" y="75" fill="#4a9eff" font-size="12" font-family="sans-serif">x</text><circle cx="195" cy="50" r="5" fill="#ffcc00"/><text x="200" y="48" fill="#ffcc00" font-size="12" font-family="sans-serif">P(3,2)</text><circle cx="65" cy="50" r="5" fill="#00ff88"/><text x="20" y="48" fill="#00ff88" font-size="12" font-family="sans-serif">P\'(−3,2)</text><line x1="65" y1="50" x2="195" y2="50" stroke="#c9d1d9" stroke-width="1.5" stroke-dasharray="5,4"/><circle cx="130" cy="50" r="3" fill="#c9d1d9"/></svg>',
        'Přes osu <b>x = k</b> (svislá přímka): vzdálenost od x = k zůstane, ale strana se prohodí.'] },
  { h: 'Vlastnosti a příklady ze života',
    p: ['Souměrnost zachovává vzdálenosti a úhly (jde o shodné zobrazení).',
        'Příklady os souměrnosti: čtverec (4 osy), obdélník (2 osy), rovnoramenný trojúhelník (1 osa), kružnice (∞ os), písmena A, M, T, V.'] },
 ],
 formulas: [
  '<b>Přes osu y:</b> (x, y) → (−x, y)',
  '<b>Přes osu x:</b> (x, y) → (x, −y)',
  '<b>|XS| = |SX\'|</b>, S = průsečík XX\' s osou',
 ],
 examples: [
  { q: 'Bod A[2, 1] zobrazíme přes osu y. Najdi A\'.', s: ['Přes osu y: x → −x', 'A\'[<b>−2, 1</b>]'] },
  { q: 'Bod B[5, 3] zobrazíme přes osu x. Najdi B\'.', s: ['Přes osu x: y → −y', 'B\'[<b>5, −3</b>]'] },
  { q: 'Kolik os souměrnosti má rovnoramenný (ne rovnostranný) trojúhelník?', s: ['Jen osa procházející vrcholem mezi shodnými rameny', '→ <b>1 osa</b>'] },
 ],
 video: { id: 'Yp5u-LyQUXQ', title: 'Osová souměrnost' },
},

'6-2': {
 mistakes: [
  {wrong:'Přes střed O mění jen jednu souřadnici', right:'(x, y) → (−x, −y) — mění se OBĚ', why:'Středová souměrnost = otočení o 180°, obě souřadnice změní znaménko. Jen jednu mění osová souměrnost.'},
  {wrong:'Přes S[3,4]: B[1,2] → (3−1, 4−2) = (2, 2)', right:'obraz = 2S − X → (2·3−1, 2·4−2) = (5, 6)', why:'Vzorec je 2S − X, ne S − X. Střed leží uprostřed úsečky bod–obraz, ne v koncovém bodě.'},
  {wrong:'Osová a středová souměrnost dají stejný obraz', right:'osová zrcadlí, středová otočí o 180°', why:'Osový obraz je zrcadlový (zamění levou/pravou stranu), středový je otočený a nezrcadlí.'},
 ],
 intro: '🌗 Duch středu říká: „Každý bod má svůj pár přes střed souměrnosti." Pochop středovou souměrnost a projdi dalším portálem!',
 sections: [
  { h: 'Středová souměrnost',
    p: ['Zobrazení, při němž <b>střed souměrnosti S</b> je středem úsečky spojující bod X a jeho obraz X\'.',
        'Ekvivalentní otočení o 180° kolem bodu S.',
        'Výpočetní vzorec: <b>X\' = 2S − X</b> (každá souřadnice zvlášť).'] },
  { h: 'Jak sestrojit obraz bodu',
    p: ['1. Spojíme bod X se středem S.',
        '2. Prodloužíme úsečku XS za S o stejnou vzdálenost.',
        '3. Tím dostaneme X\'. &ensp; Nebo: X\' = (2a − x, 2b − y) pro střed S(a, b).',
        '<svg width="260" height="160" style="display:block;margin:8px auto 0" viewBox="0 0 260 160"><line x1="130" y1="10" x2="130" y2="150" stroke="#4a9eff" stroke-width="2"/><line x1="10" y1="80" x2="250" y2="80" stroke="#4a9eff" stroke-width="2"/><polygon points="130,10 125,22 135,22" fill="#4a9eff"/><polygon points="250,80 238,75 238,85" fill="#4a9eff"/><text x="135" y="20" fill="#4a9eff" font-size="12" font-family="sans-serif">y</text><text x="238" y="75" fill="#4a9eff" font-size="12" font-family="sans-serif">x</text><circle cx="190" cy="45" r="5" fill="#ffcc00"/><text x="195" y="43" fill="#ffcc00" font-size="12" font-family="sans-serif">P(3,2)</text><circle cx="70" cy="115" r="5" fill="#00ff88"/><text x="16" y="128" fill="#00ff88" font-size="12" font-family="sans-serif">P\'(−3,−2)</text><circle cx="130" cy="80" r="5" fill="#ff5555"/><text x="135" y="95" fill="#ff5555" font-size="12" font-family="sans-serif">S(0,0)</text><line x1="190" y1="45" x2="70" y2="115" stroke="#c9d1d9" stroke-width="1.5" stroke-dasharray="5,4"/></svg>'] },
  { h: 'Středová souměrnost přes počátek',
    p: ['Pro střed O[0, 0]: (x, y) → (−x, −y). Obě souřadnice změní znaménko.',
        'Pro obecný střed S[a, b]: x\' = 2a − x, &ensp; y\' = 2b − y.'] },
  { h: 'Porovnání: osová vs. středová',
    p: ['<b>Osová:</b> obraz je zrcadlový (levá a pravá ruka se zamění).',
        '<b>Středová:</b> obraz je otočen o 180°, není zrcadlový.',
        'Středově souměrné obrazce: kružnice, čtverec, obdélník, rovnoběžník, písmena S, Z, N.'] },
 ],
 formulas: [
  '<b>Obraz X přes S:</b> X\' = 2S − X',
  '<b>Přes O[0,0]:</b> (x, y) → (−x, −y)',
 ],
 examples: [
  { q: 'A[3, 5] zobrazíme přes O[0, 0]. Najdi A\'.', s: ['A\' = (−3, −5)'] },
  { q: 'B[1, 2] zobrazíme přes S[3, 4]. Najdi B\'.', s: ['x\' = 2×3 − 1 = 5, &ensp; y\' = 2×4 − 2 = 6', 'B\'[<b>5, 6</b>]'] },
  { q: 'Má písmeno N střed souměrnosti?', s: ['Otoč N o 180° kolem středu — vypadá stejně', '→ <b>ANO, je středově souměrné</b>'] },
 ],
 video: { id: 'XCEX14hh_t0', title: 'Středová souměrnost' },
},

'6-3': {
 mistakes: [
  {wrong:'Shoda všech tří úhlů (uuu) stačí ke shodnosti', right:'uuu dává jen podobnost, ne shodnost', why:'Stejné úhly mají i zvětšené/zmenšené trojúhelníky. Ke shodnosti je nutná i délka aspoň jedné strany.'},
  {wrong:'Dvě strany a nepřilehlý úhel (SSU) vždy určí shodnost', right:'obecně ne — existují dva různé trojúhelníky', why:'Věta SSU obecně neplatí; funguje jen výjimka Ssu u pravoúhlých trojúhelníků (přepona + odvěsna).'},
  {wrong:'V zápisu ABC ≅ DEF nezáleží na pořadí vrcholů', right:'pořadí musí sedět: A↔D, B↔E, C↔F', why:'Zápis říká, které vrcholy si odpovídají. Přeházené pořadí označuje jiné dvojice stran a úhlů.'},
 ],
 intro: '🔺 Kněz shodnosti tě prověří na věty o shodnosti trojúhelníků. Zvládneš je všechny a otevřeš posvátnou schránu?',
 sections: [
  { h: 'Shodnost trojúhelníků',
    p: ['Dva trojúhelníky jsou <b>shodné (≅)</b>, pokud se jeden dá na druhý překrýt posuvem, otočením nebo převrácením.',
        'Mají stejné délky všech tří stran a stejné velikosti všech tří úhlů.'] },
  { h: 'Věty o shodnosti — stačí 3 prvky',
    p: ['Ke shodnosti NESTAČÍ zkontrolovat všech 6 prvků — stačí <b>3 správně zvolené</b>.',
        '<b>Věta sss:</b> shodují se všechny tři strany. △ABC ≅ △DEF, pokud a=d, b=e, c=f.',
        '<b>Věta sus (= SAS):</b> dvě strany a úhel <i>jimi sevřený</i>.',
        '<b>Věta usu (= ASA):</b> jedna strana a dva přilehlé úhly.',
        '<b>Věta Ssu (přepona + odvěsna):</b> platí pro pravoúhlé trojúhelníky (přepona + 1 odvěsna).'] },
  { h: 'Pozor: SSU obecně neplatí',
    p: ['Dvě strany a <i>nepřilehlý</i> úhel (SSU) obecně <b>nestačí</b> ke shodnosti — existují dva různé trojúhelníky splňující tyto podmínky.',
        'Výjimka: pro pravoúhlé trojúhelníky věta Ssu funguje.'] },
  { h: 'Jak zapsat shodnost',
    p: ['Pořadí vrcholů v zápisu △ABC ≅ △DEF musí odpovídat: A↔D, B↔E, C↔F.',
        'Postup: 1) pojmenuj trojúhelníky; 2) urči rovné prvky; 3) cituj větu; 4) napiš závěr.'] },
 ],
 formulas: [
  '<b>Věta sss:</b> a=a\', b=b\', c=c\'',
  '<b>Věta sus:</b> a=a\', úhel jimi sevřený stejný, c=c\'',
  '<b>Věta usu:</b> a=a\', α=α\', β=β\'',
 ],
 examples: [
  { q: '△ABC: a=5, b=7, c=9; △DEF: d=5, e=7, f=9. Jsou shodné?', s: ['Shodují se všechny tři strany → <b>věta sss</b>', '△ABC ≅ △DEF ✓'] },
  { q: 'AB = DE, AC = DF, úhel A = úhel D. Která věta?', s: ['Dvě strany a úhel jimi sevřený → <b>věta sus</b>'] },
  { q: 'Stačí ke shodnosti shoda všech tří úhlů (uuu)?', s: ['Stejné úhly mají i podobné trojúhelníky různé velikosti', '→ <b>NE</b>, uuu zaručuje jen podobnost, ne shodnost'] },
 ],
 video: { id: 'ycpR3sbBwbA', title: 'Konstrukce trojúhelníku — věta USU' }
},

/* ─── Oblast 7: VELKÁ PYRAMIDA ─────────────────────────────────── */

'7-1': {
 mistakes: [
  {wrong:'Obsah rovnoběžníku = a × (délka boční strany)', right:'S = a · v, kde v je KOLMÁ výška', why:'Do vzorce patří kolmá vzdálenost základen, ne délka šikmého ramene (to je delší).'},
  {wrong:'Obsah lichoběžníku = (a + c) · v', right:'S = (a + c)/2 · v', why:'Chybí dělení dvěma — bereš PRŮMĚR obou základen, ne jejich součet.'},
  {wrong:'Obsah trojúhelníku = a · v_a', right:'S = a · v_a / 2', why:'Trojúhelník je půlka rovnoběžníku, proto se dělí dvěma.'},
 ],
 intro: '🟫 Dlaždič velké pyramidy pokládá různé čtyřúhelníkové dlaždice. Musíš spočítat jejich obsahy — každá má jiný vzorec!',
 sections: [
  { h: 'Čtverec a obdélník',
    p: ['<b>Čtverec:</b> S = a². &ensp; <b>Obdélník:</b> S = a · b. (Platilo již v 6. třídě — jen připomenutí.)'] },
  { h: 'Rovnoběžník',
    p: ['Rovnoběžník: dvě dvojice rovnoběžných stran. Obsah <b>S = a · v</b>, kde v je <b>výška</b> (kolmá vzdálenost rovnoběžných stran — ne délka boční strany!).',
        '<svg width="260" height="100" style="display:block;margin:8px auto 0" viewBox="0 0 260 100"><polygon points="40,90 200,90 230,20 70,20" fill="none" stroke="#4a9eff" stroke-width="2"/><line x1="200" y1="20" x2="200" y2="90" stroke="#ffcc00" stroke-width="2" stroke-dasharray="6,4"/><rect x="195" y="85" width="10" height="10" fill="none" stroke="#ffcc00" stroke-width="1.5"/><text x="110" y="108" fill="#c9d1d9" font-size="14" font-family="sans-serif">a</text><text x="206" y="60" fill="#ffcc00" font-size="13" font-family="sans-serif">v</text></svg>'] },
  { h: 'Trojúhelník',
    p: ['<b>S = (a · v<sub>a</sub>) / 2</b>. Výška v<sub>a</sub> musí být kolmá k základně a.'] },
  { h: 'Lichoběžník',
    p: ['Lichoběžník: jedna dvojice rovnoběžných stran — základny <i>a</i> a <i>c</i>, ostatní jsou ramena.',
        '<b>S = ((a + c) / 2) · v</b> — průměr základen × výška.',
        'Logika: lichoběžník je „průměr" obdélníku s jednou základnou <i>a</i> a druhou <i>c</i>.'] },
 ],
 formulas: [
  '<b>Čtverec:</b> S = a²',
  '<b>Obdélník:</b> S = a · b',
  '<b>Rovnoběžník:</b> S = a · v  (v ⊥ a)',
  '<b>Trojúhelník:</b> S = a · v<sub>a</sub> / 2',
  '<b>Lichoběžník:</b> S = (a + c) / 2 · v',
 ],
 examples: [
  { q: 'Rovnoběžník: základna 8 cm, výška 5 cm. Obsah?', s: ['S = 8 × 5 = <b>40 cm²</b>'] },
  { q: 'Lichoběžník: základny 6 cm a 10 cm, výška 4 cm. Obsah?', s: ['S = (6 + 10)/2 × 4 = 8 × 4 = <b>32 cm²</b>'] },
  { q: 'Trojúhelník má obsah 24 cm² a základnu 8 cm. Jaká je výška na tuto základnu?', s: ['S = a · v / 2 → 24 = 8 · v / 2 = 4v', 'v = 24 / 4 = <b>6 cm</b>'] },
 ],
 video: { id: 'X5Xc16Z8GXc', title: 'Obsah lichoběžníku' },
},

'7-2': {
 mistakes: [
  {wrong:'1 m³ = 1 000 cm³', right:'1 m³ = 1 000 000 cm³', why:'Objemové jednotky mají krok 1000, ale mezi m a cm jsou DVA kroky (m → dm → cm): 1000 × 1000.'},
  {wrong:'Povrch kvádru = a·b + b·c + a·c', right:'S = 2·(a·b + b·c + a·c)', why:'Každá ze tří stěn je na tělese dvakrát (protilehlé páry), proto krát 2.'},
  {wrong:'Objem a povrch mají stejnou jednotku', right:'objem cm³, povrch cm²', why:'Objem plní vnitřek (třetí mocnina jednotky), povrch je obal (druhá mocnina). Hlídej jednotku v otázce.'},
 ],
 intro: '📦 Strážce hrobky ohlídá kvádr plný pokladů. Musíš spočítat povrch i objem — jinak tě zamkne uvnitř navždy!',
 sections: [
  { h: 'Co je hranol?',
    p: ['<b>Hranol</b> = těleso s dvěma shodnými a rovnoběžnými podstavami (n-úhelníky) a bočními stěnami (obdélníky).',
        'Nejčastěji řešíme: <b>kvádr</b> (obdélníkové podstavy) a <b>trojboký hranol</b> (trojúhelníkové podstavy).'] },
  { h: 'Objem hranolu',
    p: ['<b>V = S<sub>p</sub> × h</b>, kde S<sub>p</sub> = obsah podstavy, h = výška hranolu.',
        'Kvádr: V = a · b · c (strany a, b, c).',
        '<svg width="260" height="130" style="display:block;margin:8px auto 0" viewBox="0 0 260 130"><polygon points="40,110 120,110 150,75 70,75" fill="none" stroke="#4a9eff" stroke-width="2"/><polygon points="40,30 120,30 150,0 70,0" fill="none" stroke="#4a9eff" stroke-width="2" stroke-dasharray="4,3"/><line x1="40" y1="30" x2="40" y2="110" stroke="#4a9eff" stroke-width="2"/><line x1="120" y1="30" x2="120" y2="110" stroke="#4a9eff" stroke-width="2"/><line x1="150" y1="0" x2="150" y2="75" stroke="#4a9eff" stroke-width="2"/><line x1="70" y1="0" x2="70" y2="75" stroke="#4a9eff" stroke-width="1.5" stroke-dasharray="4,3"/><text x="72" y="125" fill="#c9d1d9" font-size="13" font-family="sans-serif">trojúhelník S<tspan baseline-shift="sub" font-size="10">p</tspan></text><text x="160" y="42" fill="#ffcc00" font-size="13" font-family="sans-serif">h</text><line x1="155" y1="5" x2="155" y2="70" stroke="#ffcc00" stroke-width="1.5" stroke-dasharray="4,3"/></svg>'] },
  { h: 'Povrch hranolu',
    p: ['<b>S = 2 · S<sub>p</sub> + o · h</b>, kde o = obvod podstavy.',
        'Kvádr: S = 2(ab + bc + ac) = 2 × (součet tří různých stěn).',
        'Trojboký hranol: S = 2 × S<sub>p</sub> + (a<sub>1</sub> + a<sub>2</sub> + a<sub>3</sub>) × h.'] },
  { h: 'Jednotky objemu',
    p: ['1 m³ = 1 000 000 cm³ (= 10<sup>6</sup> cm³). &ensp; 1 dm³ = 1 litr = 1 000 cm³.',
        'Přepočet: 1 m³ = 1 000 dm³ = 1 000 litrů.'] },
 ],
 formulas: [
  '<b>Objem hranolu:</b> V = S<sub>p</sub> · h',
  '<b>Povrch kvádru:</b> S = 2(ab + bc + ac)',
  '<b>Povrch hranolu:</b> S = 2·S<sub>p</sub> + o·h',
 ],
 examples: [
  { q: 'Kvádr: a = 5 cm, b = 4 cm, c = 3 cm. Objem a povrch?', s: ['V = 5 × 4 × 3 = <b>60 cm³</b>', 'S = 2(5×4 + 4×3 + 5×3) = 2(20+12+15) = 2×47 = <b>94 cm²</b>'] },
  { q: 'Hranol s pravoúhlou trojúh. podstavou (odvěsny 3 a 4 cm) a výškou 10 cm. Objem?', s: ['S<sub>p</sub> = (3 × 4)/2 = 6 cm²', 'V = 6 × 10 = <b>60 cm³</b>'] },
  { q: 'Bazén 5 × 3 × 2 m. Kolik litrů vody se do něj vejde?', s: ['V = 5 × 3 × 2 = 30 m³', '1 m³ = 1 000 l → <b>30 000 litrů</b>'] },
 ],
 video: { id: 'LUgKaMWPels', title: 'Objem a povrch hranolu' },
},

'7-3': {
 mistakes: [
  {wrong:'1/2 + 1/3 = 2/5', right:'3/6 + 2/6 = 5/6', why:'Jmenovatele se nesčítají — nejdřív sjednoť na NSN, pak sečti čitatele.'},
  {wrong:'Po zdražení o 20 % je 360 Kč, původní = 360 : 0,20', right:'C = 360 : 1,20 = 300 Kč', why:'360 Kč odpovídá 120 % původní ceny. Dělí se 1,20, ne procentem změny.'},
  {wrong:'−3² = 9', right:'−3² = −9; jen (−3)² = 9', why:'Bez závorky se umocňuje jen trojka, minus zůstává vepředu.'},
 ],
 intro: '🗿 Strážce pyramidy — finální boss! Prověří tě ze všech témat Ztraceného chrámu. Připrav se a osvěž si klíčové vzorce!',
 sections: [
  { h: 'Oblast 1: Čísla a základní geometrie',
    p: ['<b>Desetinná čísla:</b> zarovnávej čárky (sčítání/odčítání), sčítej des. místa (násobení), odstraňuj čárku ze jmenovatele (dělení).',
        '<b>Obsahy:</b> čtverec a², obdélník ab, trojúhelník av/2, rovnoběžník av.',
        '<b>Tip:</b> před výpočtem si vždy odhadni výsledek — zachytíš hrubé chyby.'] },
  { h: 'Oblast 2–3: Zlomky a celá čísla',
    p: ['<b>Zlomky:</b> krácení (: NSD), rozšiřování (× k), sčítání (→ NSN), násobení (čitatel×čitatel, jmenovatel×jmenovatel), dělení (× převrácený).',
        '<b>Celá čísla:</b> (−)×(−)=(+), (−)×(+)=(−). (−3)² = 9, ale −3² = −9.',
        '<b>Racionální čísla ℚ:</b> vše, co lze zapsat jako p/q (q≠0). Absolutní hodnota |a| = vzdálenost od nuly.'] },
  { h: 'Oblast 4–5: Poměr, trojčlenka, procenta',
    p: ['<b>Poměr:</b> zjednoduš (: NSD), rozděl celek (spočítej 1 díl).',
        '<b>Trojčlenka:</b> přímá (y = kx, urči 1 jednotku), nepřímá (xy = k, urči součin).',
        '<b>Procenta:</b> z = C·p/100; p = z/C·100; C = z·100/p. Sleva: ×(1−p/100), zdražení: ×(1+p/100), zpětný výpočet: :(1−p/100).'] },
  { h: 'Oblast 6–7: Geometrie',
    p: ['<b>Osová souměrnost:</b> osa = osa úsečky XY; přes osu y: (x,y)→(−x,y).',
        '<b>Středová souměrnost:</b> X\' = 2S−X; přes O: (x,y)→(−x,−y).',
        '<b>Shodnost:</b> věty sss, sus (SAS), usu (ASA), Ssu (pravoúhlý).',
        '<b>Obsahy čtyřúhelníků:</b> rovnoběžník av, lichoběžník (a+c)/2·v.',
        '<b>Hranol:</b> V = S<sub>p</sub>·h; povrch = 2S<sub>p</sub> + o·h.'] },
  { h: 'Tipy pro slovní úlohy',
    p: ['1. Přečti zadání 2×. Vypiš, co víš a co hledáš.',
        '2. Nakresli si obrázek nebo tabulku (pomáhá hlavně u trojčlenky a geometrie).',
        '3. Zvolte správný vzorec a dosaďte — <b>se správnými jednotkami</b>.',
        '4. Zkontroluj: je výsledek rozumný? (odhad, kontrola zpět)'] },
 ],
 formulas: [
  '<b>Zlomky:</b> a/b : c/d = a/b × d/c',
  '<b>Procenta:</b> z = C × p/100',
  '<b>Trojčlenka přímá:</b> x₁:y₁ = x₂:y₂',
  '<b>Lichoběžník:</b> S = (a+c)/2 × v',
  '<b>Hranol:</b> V = S<sub>p</sub> × h',
 ],
 examples: [
  { q: 'Jak se počítá povrch hranolu?', s: ['S = 2 · S<sub>p</sub> + o · h', 'kde S<sub>p</sub> = obsah podstavy, o = obvod podstavy, h = výška hranolu'] },
  { q: 'Kolik je 15 % z 240?', s: ['z = 240 × 15/100 = 240 × 0,15 = <b>36</b>'] },
  { q: 'Po zdražení o 20 % stojí věc 360 Kč. Kolik stála původně?', s: ['360 = C × 1,20', 'C = 360 / 1,20 = <b>300 Kč</b>'] },
 ],
 video: { id: 'RbkRs2cS8dk', title: 'CERMAT 2023 — přijímací zkoušky' }
},

};
})();
